### ISSUE TITLE
[PORT] Adds serialization fix for #3833

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#1033]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3845

Added code to ensure that InvokeResponse values are deserialized as InvokeResponse (they come as JObject in C# by default)

# Changed projects
* Microsoft.Bot.Builder.Dialogs

[R9]

**Comment by gabog** [comment]
NA, will be handled as part of #1026
