### ISSUE TITLE
[PORT] MetadataBoost dead code cleanup

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#1035]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3751

fixes #3723 

# Changed projects
* Microsoft.Bot.Builder.AI.QnA
* Microsoft.Bot.Builder.AI.QnA.Tests

**Comment by vipeketi** [comment]
No impact. @tomlm
