### ISSUE TITLE
Display HTML formatted table in Web Chat control 

### ISSUE THREAD

**Issue by vijaysaimutyala** [Microsoft/botbuilder-python#105]
I'm trying to display a table in the web chat channel. I understand that Web Chat uses markdown for rendering text. But in the [link](https://github.com/Microsoft/BotBuilder/issues/2785) suggests that we can pass textFormat to the activity to display a simple HTML table.

I tried passing the textFormat as 'xml' and a html table in the message content, but the web chat shows just the html content not the formatted table and I see the below in my log after the message is posted.

> msrest.service_client:Accept header absent and forced to application/json

And I googled a bit and found that [ms-rest for python](https://github.com/Azure/msrest-for-python)==0.5.4 library has upgrades to support xml formatting and [botbuilder-schema==4.0.0a6](https://github.com/Microsoft/botbuilder-python/blob/master/libraries/botbuilder-schema/setup.py) currently uses **msrest==0.4.29**.

So is this the issue which is not rendering the html table properly. If not, what can be done so that I could send a clean table format to the bot in web chat. I tried sending markdown formatted tables using [tabulate](https://github.com/gregbanks/python-tabulate) but it does not look good. Also tried using adaptive card, but with the amount of data I want to show, the adaptive cards does not seem to be a nice [choice](https://github.com/Microsoft/AdaptiveCards/issues/1786)

**Comment by vijaysaimutyala** [comment]
Not sure if the msrest version needs to be bumped because of the above mentioned log, I further did a bit of more research and found that HTML support for webchat was turned off by default. If someone wants to use HTML, they're suggested to build their own version of Web Chat by enabling the inline HTML support for Markdown as mentioned [here](https://blog.botframework.com/2017/09/07/html-not-supported-web-chat/). 

I suppose this issue can be closed as the msrest has nothing to do with the HTML display on webchat as I assumed.

**Comment by corinagum** [comment]
Glad you were able to figure it out. Closing this issue.
