### ISSUE TITLE
[Incomplete/Bug in documentation] samples folder missing

### ISSUE THREAD

**Issue by Maijin** [microsoft/botbuilder-python#1060]
Greetings Team,

The [official documentation](https://docs.microsoft.com/en-us/azure/bot-service/python/bot-builder-python-samples?view=azure-bot-service-4.0) mention samples folder that is not available in the repository.

The samples I found so far are here https://github.com/microsoft/BotBuilder-Samples/tree/master/generators/python
https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/python/01.console-echo

**Comment by tracyboehrer** [comment]
@Maijin Where is the reference in the docs to that?  There is a 01.console-echo sample, but not in the path ("generators") you list.

**Comment by Maijin** [comment]
@tracyboehrer - The documentation claims that https://github.com/microsoft/botbuilder-python/ contains a samples folder which doesn't exist - that's the problem.

The references I posted may be what is this samples/ supposed to be. I don't work at microsoft so I have no idea :/ but that official documentation is definitely incomplete/wrong and should be fixed as samples are essentials to get a grasp on how to use botbuilder-python 👍

**Comment by tracyboehrer** [comment]
@Maijin I see what you are saying. That document is out of date. All of the Python samples exist in the BotBuilder-Samples repository. 

You can find them at:

https://github.com/microsoft/BotBuilder-Samples

We will correct the document with the outdated link.

**Comment by Maijin** [comment]
thanks!

**Comment by tracyboehrer** [comment]
Closing.  Docs issue opened at: https://github.com/MicrosoftDocs/bot-docs/issues/1705
