### ISSUE TITLE
Dependency mismatch

### ISSUE THREAD

**Issue by laxas** [microsoft/botbuilder-python#1070]
## Version
4.9.0

## Describe the bug
Some of the packages require requests exactly in version 2.22.0. Cookiecutter requires requests >= 2.23.0. The installation described in https://docs.microsoft.com/en-us/azure/bot-service/python/bot-builder-python-quickstart?view=azure-bot-service-4.0 is not possible in a singe venv.

## To Reproduce
1. Go to Linux terminal
2. Write
```bash
cd /tmp
mkdir teamsbot
cd teamsbot
poetry init
# answer poetry init questions with defaults 
poetry add botbuilder-core 
poetry add asyncip
poetry add cookiecutter
````
3. See error

## Expected behavior
Coplete installation

## Screenshots
[SolverProblemError]
Because no versions of botframework-connector match >4.7.1,<4.8.0 || >4.8.0,<4.9.0 || >4.9.0
 and botframework-connector (4.7.1) depends on requests (2.22.0), botframework-connector (>=4.7.1,<4.8.0 || >4.8.0,<4.9.0 || >4.9.0) requires requests (2.22.0).
And because botframework-connector (4.8.0) depends on requests (2.22.0)
 and botframework-connector (4.9.0) depends on requests (2.22.0), botframework-connector (>=4.7.1) requires requests (2.22.0).
Because no versions of botbuilder-core match >4.9.0,<5.0.0
 and botbuilder-core (4.9.0) depends on botframework-connector (>=4.7.1), botbuilder-core (>=4.9.0,<5.0.0) requires botframework-connector (>=4.7.1).
Thus, botbuilder-core (>=4.9.0,<5.0.0) requires requests (2.22.0).
So, because demo depends on both requests (^2.23.0) and botbuilder-core (^4.9.0), version solving failed.

[bug]

**Comment by tracyboehrer** [comment]
@laxas Thank you for reporting this.  We will get this resolved in the next release.

**Comment by tracyboehrer** [comment]
@laxas It appears if you install the 1.7.0 version of CookieCutter it will work as expected.

pip install cookiecutter==1.7.0
