### ISSUE TITLE
async/await keyword is only used from Python 3.5 or above.

### ISSUE THREAD

**Issue by koshtinikhilesh** [Microsoft/botbuilder-python#108]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Kindly update README.md file (https://github.com/Microsoft/botbuilder-python/blob/master/samples/Rich-Cards-Bot/README.md) for Python3.5.
In Python lower version, it state error :-- 
 File "main.py", line 32
    async def create_reply_activity(request_activity, text) -> Activity:
            ^
SyntaxError: invalid syntax

**Describe alternatives you've considered**

**Additional context**

[enhancement]

**Comment by stevengum** [comment]
Closing via #111's merge. Thanks for reporting!
