### ISSUE TITLE
Teams shows "bad request" when a skill invocation ends

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botbuilder-python#1087]
Python Version of:
https://github.com/microsoft/botbuilder-dotnet/issues/3956
https://github.com/microsoft/botbuilder-js/issues/2265

## Version
4.9.1

## Describe the bug
When you call a skill from a bot on teams you'll get a "bad request" message when the skill ends.  I believe this is related to the issue of the post back completing on a second thread.

![image](https://user-images.githubusercontent.com/698939/82462434-6af9ec80-9a70-11ea-88c0-b2935ce5b22e.png)

[bug]

**Comment by tracyboehrer** [comment]
This requires DialogManager

**Comment by cleemullins** [comment]
This is blocked waiting on the port of Dialog Manager in Python. I believe that will land in R11.

**Comment by gabog** [comment]
@axelsrz / @cleemullins, will DialogManager be in Python for R11? or we should move this one to the backlog and remove it from the milestone?
