### ISSUE TITLE
[PORT] Fixes BadRequest message in Teams (#3966)

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#1090]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3967

* Added check to ensure we don't send EoC when a skill is done and we are at the root bot.
Updated tests to handle this case and removed duplicated test after refactoring.
Fixed some typos and trace message names.

# Changed projects
* Microsoft.Bot.Builder.Dialogs
* Microsoft.Bot.Builder.Dialogs.Tests

**Comment by gabog** [comment]
NA
