### ISSUE TITLE
[PORT] Hardened prompts

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#1091]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3949

See parent PR: https://github.com/microsoft/botbuilder-js/pull/2246

## Description

Some of the prompts break if user uploads an attachment instead of responding with text because of some of the `string` methods that get called on `activity.text` (which doesn't exist if an attachment is sent).

## Specific Changes

Add some variation of

```csharp
if (string.isNullOrEmpty(turnContext.Activity.Text)) {
  return Task.FromResult(result);
}
```

to:

1. ChoicePrompt
2. DatetimePrompt
3. NumberPrompt
4. ConfirmPrompt

I also renamed `message` to `utterance` to be more in line with other prompts.

The original issue was only for DatetimePrompt, but I added the other two. Other prompts didn't seem relevant for this.

# Changed projects
* Microsoft.Bot.Builder.Dialogs

**Comment by mdrichardson** [comment]
Already merged: https://github.com/microsoft/botbuilder-python/pull/1074
