### ISSUE TITLE
cant clone the requirements.txt

### ISSUE THREAD

**Issue by Ramanirajesh** [microsoft/botbuilder-python#112]
Command "git checkout -q a997e97cd926c1eedfe4e5a3a52a637313fbd4e4" failed with error code 128 in /private/var/folders/59/c59yst8s6dnd_gk0xdd4t_340000gn/T/pip-req-build-ZkQZiP

**Comment by saideepchandg** [comment]
Unable to install requirements.txt. It fails with the error: 

> fatal: reference is not a tree: a997e97cd926c1eedfe4e5a3a52a637313fbd4e4


![image](https://user-images.githubusercontent.com/11366144/48959940-1a92f300-ef8f-11e8-8f85-a9751e7a8a04.png)

I am trying to install the requirements.txt under '_botbuilder-python\samples\Rich-Cards-Bot_'

**Comment by heitorrapela** [comment]
I had installed it, but I could not anymore and I don`t know why *.*

**Comment by heitorrapela** [comment]
Hello, try this in your requirements.txt:
```
git+https://github.com/Azure/msrest-for-python@v0.4.29
botbuilder-core
botframework-connector
botbuilder-schema
requests>=2.18.1
PyJWT==1.5.3
cryptography==2.1.4
aiohttp==3.1
```

**Comment by sgellock** [comment]
fixed in preview b2
