### ISSUE TITLE
[PORT] Sets warnings as errors and adds FxCop analyzer to Schema project.

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#1127]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4061

Relates to #2367.

- Configured TreatWarningsAsErrors on all projects in the libraries folder except for Microsoft.Bot.Builder.Dialogs.Adaptive.Testing (that needs to be addressed separately).
- Created Directory.Build.props for FunctionalTests and Tests to manage excludes for the projects in those folders.
- Edited projects to generate XML documentation for debug config too so we can catch this early on rather than later in the build server. 
- Added NoWarn properties for documentation on each project (these will be addressed by #4052).
- Fixed long hanging fruit warnings.
- Added Roslyn FxCop analyzer to Microsoft.Bot.Schema and fixed violations or excluded them using #pragma with justification for the exclude (most of the changes couldn't be made because of binary compat).

# Changed projects
* Adapters
* AdaptiveExpressions
* Microsoft.Bot.Builder.AI.LUIS
* Microsoft.Bot.Builder.AI.QnA
* Microsoft.Bot.Builder.ApplicationInsights
* Microsoft.Bot.Builder.Azure
* Microsoft.Bot.Builder.Dialogs.Adaptive.Testing
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.Dialogs.Debugging
* Microsoft.Bot.Builder.Dialogs.Declarative
* Microsoft.Bot.Builder.Dialogs
* Microsoft.Bot.Builder.LanguageGeneration
* Microsoft.Bot.Builder.TemplateManager
* Microsoft.Bot.Builder.Testing
* Microsoft.Bot.Builder
* Microsoft.Bot.Configuration
* Microsoft.Bot.Connector
* Microsoft.Bot.Schema
* Microsoft.Bot.Streaming
* integration
* 
* Microsoft.Bot.Schema.Tests

**Comment by axelsrz** [comment]
N/A
