### ISSUE TITLE
[PORT] disable unused codeSignValidationInjection task in main CI

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#1152]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4056

Partially addresses: #4055

Build [137843](https://fuselabs.visualstudio.com/SDK_Public/_build/results?buildId=137843&view=results) for these changes has a total duration of 21min and 16s:

![image](https://user-images.githubusercontent.com/14935595/84454478-783d6d80-ac0f-11ea-9ff6-3adc99f647a2.png)

The last successful build ([137707](https://fuselabs.visualstudio.com/SDK_Public/_build/results?buildId=137707&view=results)) took 27min 12s to complete:

![image](https://user-images.githubusercontent.com/14935595/84454584-bdfa3600-ac0f-11ea-934a-0ad1d6d5a4f7.png)

___

This PR speeds up the build by disabling the auto-injected "Run Codesign Validation" task, which was running at the end of our stages.  This task automaically fetches an internal tool for the codesign validation step and applicable .NET Core SDKs before eventually skipping the workflow, a process that takes around one minute.

Searching for the variable name, there were other Microsoft projects that also disabled this task as it was N/A. (https://github.com/microsoft/terminal/pull/4387 and https://github.com/microsoft/react-native-windows/pull/3923)

**Comment by stevengum** [comment]
N/A this task is already skipped
