### ISSUE TITLE
[PORT] Fixes issue #3960 [QnAMaker] [DotNet] Implementing QnAMaker's precise answering capability as an additional feature for BotFramework users

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#1155]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3935

Fixes issue #3960

QnAMaker has new additional feature,  to provide answers in precise.  Users can choose to use this feature by sending an additional parameter, during GenerateAnswer API call. 

# Changed projects
* Microsoft.Bot.Builder.AI.QnA
* Microsoft.Bot.Builder.AI.QnA.Tests

[changes required]

**Comment by mrivera-ms** [comment]
The associated PR in the dotnet repo was [reverted in PR4170](https://github.com/microsoft/botbuilder-dotnet/pull/4170). We do not need this port at this point.
