### ISSUE TITLE
[Parity] ActivityEx is not present in Botbuilder-Python

### ISSUE THREAD

**Issue by gabog** [microsoft/botbuilder-python#1157]
See [dotnet source](https://github.com/microsoft/botbuilder-js/issues/1753)

**Comment by mrivera-ms** [comment]
This item is assigned to @JuanAr from Southworks. Having problems with Github at the moment.

**Comment by axelsrz** [comment]
@JuanAr @mrivera-ms @gabog  Given that Class Exentions are a C# only feature we don't have a direct file equivalent but the functionality is probably in the actual class or a helper. Is there any specif functionality missing?

**Comment by tracyboehrer** [comment]
@axelsrz I believe that in many cases, the pattern for Python would be to add the missing methods to the Activity class.

**Comment by gabog** [comment]
That's correct @tracyboehrer, we have ActivityEx in dotnet because that was generated from swagger (and it was a partial class) but moving forward we should just start  adding new methods to the main class and drop the partials for the generated ones (we'll get to that at some point in dotnet)
