### ISSUE TITLE
[PORT] Add dialogContext memory scope

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#1168]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4037

Fixes #3210 
Fixes #3363 

Add new **DialogContext** memory scope with ids of 
* activeDialog
* parent
* stack

This allows you to determine if you are executing the context of a known dialog via expression
```=contains(dialogcontext.stack,'somedialogid')```
Also added 3 utility expression functions
* **isDialogActive('dialogId')** - returns true if a given dialog id is in the stack
* **isActionActive('actionId')** - simple alias for isDialogActive to match IA for actions.
* **hasPendingActions()** - returns true if there is nothing in the execution plan for the active dialog.

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.Dialogs
* Microsoft.Bot.Builder.Dialogs.Adaptive.Tests
* Microsoft.Bot.Builder.Dialogs.Tests

**Comment by axelsrz** [comment]
N/A
