### ISSUE TITLE
No module named 'botbuilder.ai.qna.dialogs' - Python QnA Sample 49

### ISSUE THREAD

**Issue by vijaysaimutyala** [microsoft/botbuilder-python#1188]
## Version
botbuilder-ai - 4.9.1

## Describe the bug
I was trying out the QnA Maker Sample - 49.qnamaker-all-features . I've configured my QnA KB and also the config.py with the necessary info. However the module botbuilder.ai.qna.dialogs does not seem to exist. I've manually verified for the class QnAMakermDialog and it does not exist

> from botbuilder.ai.qna.dialogs import QnAMakermDialog

## To Reproduce
1. Download the sample 49.qnamaker-all-features
2. Install the necessary requirements and configure QnAMaker.
3. Run python app.py in the folder

## Expected behavior
The sample should've run successfully.

[bug]

**Comment by tracyboehrer** [comment]
@vijaysaimutyala Where are you seeing that import line?  The actual class name should be QnAMakerDialog (not QnAMakermDialog).

**Comment by vijaysaimutyala** [comment]
@tracyboehrer Sorry that might be a typo. You can look the import [here](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/python/49.qnamaker-all-features/app.py) I rectified the typo and still couldn't see the module. Below is the screenshot from my local env. I'm somehow missing the dialogs part I see on the Botbuilder-python [repo](https://github.com/microsoft/botbuilder-python/tree/c15c61523c4b69f81bddbfd49e1be910beca0cdd/libraries/botbuilder-ai/botbuilder/ai/qna/dialogs)

![image](https://user-images.githubusercontent.com/7084628/86011594-7f031780-ba3a-11ea-86d5-5b205d75a869.png)

I tried updating botbuilder-ai, but its already at 4.9.1

**Comment by vijaysaimutyala** [comment]
A quick update. I created a fresh conda environment and installed the requirements of the [sample 49](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/python/49.qnamaker-all-features) but I faced the same issue again. Also I noticed on the Samples homepage that the Python sample link is not updated yet. 

![image](https://user-images.githubusercontent.com/7084628/86012756-fd13ee00-ba3b-11ea-9caa-c46415d7d652.png)

**Comment by tracyboehrer** [comment]
@vijaysaimutyala This is a bug on our side.  We didn't provide an export for the dialogs package.

**Comment by vijaysaimutyala** [comment]
Thanks for checking @tracyboehrer Let me know if I can help in any way.

**Comment by tracyboehrer** [comment]
@vijaysaimutyala We are making the correction in the ai.qna package.  But it will require a patch release (4.9.2).  We are working though the timing on that.  This issue will automatically close out when the fix is merged though.

**Comment by Virtual-Josh** [comment]
The fix is in our next planned release. Our next release is on ~Aug 15th, but it might slide a day or so depending.
