### ISSUE TITLE
[PORT] Add ImageAltText to CardAction

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#1201]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4195

Fixes #4041

This does not add the field to the constructor, since we are moving away from the huge constructor pattern.

Verified the new field is passed through to WebChat:

![image](https://user-images.githubusercontent.com/11055362/86056302-1bfd8a80-ba12-11ea-82fe-8700d6c4612d.png)

# Changed projects
* Microsoft.Bot.Schema

**Comment by EricDahlvang** [comment]
completed with a different issue
