### ISSUE TITLE
[PORT] SwitchCondition with number throws an exception when compared against a string

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#1209]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4148

Fixes #4071 

## Description
SwitchCondition treated errors as exceptions when all that was happening was an comparison which was false. In addition, it was always assuming that a quoted number should be compared as a number. 

## Specific Changes
* Fix switch to not treat expression errors as exceptions but instead as false condition
* Fix switch to treat ambiguity in string case definition more robustly by comparing for both value type and string of value type. (23 OR "23")

## Testing
updated unit test cases to cover this.

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.Dialogs.Adaptive.Tests
* Microsoft.Bot.Builder.Dialogs.Declarative.Tests

**Comment by axelsrz** [comment]
N/A
