### ISSUE TITLE
Bot - Create new conversation

### ISSUE THREAD

**Issue by mikolus** [Microsoft/botbuilder-python#128]
I'm using the botbuilder-python to build MS Teams bot. Following samples **I am able to respond to messages**. What I'm struggling with is creating completely **new message**, without existing activity passed from Teams. I modified some code from the tests (https://github.com/Microsoft/botbuilder-python/blob/62b0512a4dd918fa0d3837207012b31213aaedcc/libraries/botframework-connector/tests/test_conversations.py) but I'm getting:

botbuilder.schema.error_response_py3.ErrorResponseException: (BadSyntax) Could not parse tenant id

What is it, where can I find it (I can fish it out from request but it's not ideal, I need to be able to message user that has never interacted with the bot before) and how do I pass it? Can anyone point me at any Python samples of creating a completely new conversation with a user that has never interacted with the bot? There is a documentation page that's supposed to explain how to request it, but it only mentions that overload requiring tenant id is obsolete:

https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-context#fetching-the-team-roster

I realize it's not really an issue, but I asked it question on Stackoverflow (https://stackoverflow.com/questions/54994012/ms-teams-bot-create-new-conversation) and got a suggestion to post it here as well.

**Comment by tdurnford** [comment]
Closing as answered on StackOverflow [Question](https://stackoverflow.com/questions/54994012/ms-teams-bot-create-new-conversation).
