### ISSUE TITLE
[PORT] Added FxCop fot TemplateManager

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#1288]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4338

Relates to #2367

- Added several #pragma disable to violations where we can't change things withouth breaking compat.

# Changed projects
* Microsoft.Bot.Builder.TemplateManager

**Comment by gabog** [comment]
na
