### ISSUE TITLE
[PORT] Changed test to use https (petco was returning 405 for http)

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#1295]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4351

Fixes HttpTests

Changed petco requests to use https instead http so the test would pass

# Changed projects
* Microsoft.Bot.Builder.TestBot.Json

**Comment by gabog** [comment]
NA
