### ISSUE TITLE
aiohttp.web

### ISSUE THREAD

**Issue by cyberf4n** [Microsoft/botbuilder-python#130]
## Version
4

Traceback (most recent call last):
  File "main.py", line 77, in <module>
    async def messages(req: web.web_request) -> web.Response:
AttributeError: module 'aiohttp.web' has no attribute 'web_request'

[bug]

**Comment by cyberf4n** [comment]
tried multiple aiohttp versions and the only one working is aiohttp==3.1

**Comment by tdurnford** [comment]
@cyberf4n 

Aiohttp removed 'web.web_request' from their releases after version 3.5.0 which the Python Samples use in the messaging endpoint functions. If you want to use version 3.5.0 or greater of Aiohttp, you must change the type of the req parameter in the messages function form 'web.web_request' to 'web.BaseRequest' or remove it altogether. This is how your messages function should look.

````python
async def messages(req: web.BaseRequest) -> web.Response:
    body = await req.json()
    activity = Activity().deserialize(body)
    auth_header = req.headers['Authorization'] if 'Authorization' in req.headers else ''
    try:
        return await ADAPTER.process_activity(activity, auth_header, bot.on_turn)
    except Exception as e:
        raise e
````

This is how I have my requirements.txt file configured.

```
git+https://github.com/Azure/msrest-for-python@v0.4.29
botbuilder-core>=4.0.0.a6
aiohttp==3.5.3
```

Hope this helps!
