### ISSUE TITLE
[PORT] Fixes Unauthorized error when calling ContinueConversation

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#1300]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4348

Fixes #4347

Fixes Unauthorized error when ContinueConversation is called on a bot app service instance that didn't originate the skill request.
- Updated code in BotFrameworkAdapter.ContinueConversation() so it always adds the activity.ServiceUrl to TrustedHostNames if the request has been authorized and it has an app ID (this will work for skills and other proactive messages)
- Made TrustedHostNames in AppCredentials internal and added InternalsVisibleTo directive to Microsoft.BotConnector so we can access it and assert the state of the state in tests.
- Cleaned up some async warnings in BotFrameworkAdapterTests
- Added additional logging to AppCredentials to help troubleshoot this issue in the future.

# Changed projects
* Microsoft.Bot.Builder
* Microsoft.Bot.Connector
* Microsoft.Bot.Builder.Tests

**Comment by gabog** [comment]
Hi @axelsrz, can you validate if the related PR applies to Python?
