### ISSUE TITLE
Language Generation (LG)

### ISSUE THREAD

**Issue by phrenol** [microsoft/botbuilder-python#1304]
Hi,

Thanks for this amazing SDK.

I noticed that the C# and JS SDK's have Language Generation (LG). Can we expect this to be added to this SDK as well? I need a nice way to separate business logic and presentation, and LG seems to be the way to do it.

Thanks

**Comment by daveta** [comment]
@phrenol : Thanks for the kind words - this is on the radar, I don't have a milestone for you yet.

**Comment by daveta** [comment]
@phrenol : LG is in planned to come in the future but not close enough that we'd have an estimate release date. Stay tuned.
