### ISSUE TITLE
Git throwing error when trying to clone latest release

### ISSUE THREAD

**Issue by aarsan** [Microsoft/botbuilder-python#137]
When trying to clone 4.0.0.a6 via this link:

https://github.com/Microsoft/botbuilder-python/releases 

Git throws the following error:

    fatal: reference is not a tree: a997e97cd926c1eedfe4e5a3a52a637313fbd4e4
    Command "git checkout -q a997e97cd926c1eedfe4e5a3a52a637313fbd4e4" failed with error 
    code 128 in C:\Users\aharsan\AppData\Local\Temp\pip-req-build-v3iwwdm4

**Comment by tdurnford** [comment]
I'd recommend trying `git checkout tags/4.0.0.a6 -b 4.0.0.a6` if are trying to checkout the latest release. 

For more information on checking out tags, take a look at Git's [documentation](https://git-scm.com/book/en/v2/Git-Basics-Tagging) and this [Question](https://stackoverflow.com/questions/791959/download-a-specific-tag-with-git) on StackOverflow.
