### ISSUE TITLE
Implement adaptive cards templating functionality 

### ISSUE THREAD

**Issue by reinoldus** [microsoft/botbuilder-python#1389]
**Is your feature request related to a problem? Please describe.**
I just designed my AdapativeCards using the templating engine only to find out that this feature is not supported in the python sdk: https://docs.microsoft.com/en-us/adaptive-cards/templating/#sdk-support

**Describe the solution you'd like**
Implementation of templating for AdaptiveCards

**Describe alternatives you've considered**
Alternative is to edit the json file in code, exactly what the templating engine wants to avoid.

**Comment by tdurnford** [comment]
@axelsrz Can you weigh in on this?

**Comment by v-kydela** [comment]
@reinoldus - This has nothing to do with Bot Builder. None of the Bot Builder SDK's incorporate Adaptive Cards templating. If you'd like the Adaptive Cards SDK to support templating in Python then you should make a feature request in the Adaptive Cards repo: https://github.com/microsoft/AdaptiveCards/issues/new/choose

**Comment by reinoldus** [comment]
Thank you for clarifying. In fact there is already a ticket. https://github.com/microsoft/AdaptiveCards/issues/3896
