### ISSUE TITLE
I can develop skills in Emulator without an app password (Python)

### ISSUE THREAD

**Issue by gabog** [microsoft/botbuilder-python#1396]
See [parent](https://github.com/microsoft/botframework-sdk/issues/5726)

**Comment by mdrichardson** [comment]
I'll start iterating on this a little, knowing that [the Dotnet PR](https://github.com/microsoft/botbuilder-dotnet/pull/4757) isn't finalized yet

**Comment by gabog** [comment]
Hi @mdrichardson, FYI the dotnet PR has been merged into main with the latest updates (see the PR summary for more details).

Thanks

**Comment by mdrichardson** [comment]
Thanks, @gabog! I'll make the updates and have the PR ready for review today.
