### ISSUE TITLE
Teams added, deleted and renamed API quite confusing?

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/botbuilder-python#1405]
## Version
4.10.1

## Describe the bug
While testing the application  on_teams_members_added , on_teams_members_removed is working fine but on_teams_team_renamed is not working instead of we have to use on_teams_team_renamed_activity api. 

**Note** : channel added , renamed , deleted events is working fine.

## Expected behavior
on_teams_team_renamed api should be work.

**Comment by mdrichardson** [comment]
@rvinothrajendran There is no internal method called `on_teams_team_renamed()`. Please only override the methods found in the [`teams_activity_handler`](https://github.com/microsoft/botbuilder-python/blob/main/libraries/botbuilder-core/botbuilder/core/teams/teams_activity_handler.py). In this case, you want to stick with [`on_teams_team_renamed_activity()`](https://github.com/microsoft/botbuilder-python/blob/main/libraries/botbuilder-core/botbuilder/core/teams/teams_activity_handler.py#L603)

**Comment by rvinothrajendran** [comment]
Thanks @mdrichardson 
My searching went wrong 😊 

APIs names are in same standard. 
1.	on_teams_members_added
2.	on_teams_members_removed
3.	on_teams_channel_created
4.	on_teams_channel_renamed
5.	on_teams_channel_deleted
but on_teams_team_renamed_activity api name is different, suffix “**activity**” has added is this any specific reason ?

**Comment by mdrichardson** [comment]
@rvinothrajendran I see what you mean.

@axelsrz @tracyboehrer I think the naming of `on_teams_team_renamed_activity` may have been a mistake. Would it make sense to add an overload named `on_teams_team_renamed` (because Python SDK is GA, right?), or should we leave this as-is?
