### ISSUE TITLE
[Tracking isssue] Can't deploy bots to Azure

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/botbuilder-python#1412]
There is an issue with deploying python bots to Azure. There's an issue with aiohttp not being installed even though there's a pinned version of it in the botbuilder-integration-aiohttp requirements. Manually adding the package also doesn't work. 

JJ apparently had a customer complain of a similar thing ~1 week ago. I'll follow up with her to add tracking details. 

I have a ticket open with Azure.

**Comment by jwiley84** [comment]
Sorry for the poor image quality, it's a screenshot of a screenshot. Josh ran into this deploying an echo bot, my cx ran into it while deploying a core-bot. The cx deployed using the CLI deployment outlined in [Deploy your bot](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=Python)

The cx in question was using python 3.5, and thought upgrading his python would help. I have not heard back from him yet.

![image](https://user-images.githubusercontent.com/17333688/96514265-41f4a800-1218-11eb-8524-e424d98f3959.png)

**Comment by Virtual-Josh** [comment]
I tried using 3.7 and 3.8 so it seems increasingly likely the problem is Azure's. I have a ticket out with them so I'll update this ticket as I have more info.

**Comment by Virtual-Josh** [comment]
There's an [ICM](https://portal.microsofticm.com/imp/v3/incidents/details/205734347/home) dealing with VA and a python skill bot that seems related.

Also yaml deployments still appear to be working as a workaround.

**Comment by Virtual-Josh** [comment]
I just tested this issue in a non-MS tenant and the issue reproduces. It seems as though the scope of the issue is much larger.

**Comment by EricDahlvang** [comment]
`Az webapp up `is also failing.

https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az_webapp_up

The pipeline deployments are using gitdeploy
```
az deployment create --name "$(BotName)-RG" --template-file "$(System.DefaultWorkingDirectory)/$(TemplateLocation)" --location "westus" --parameters appId="$(DeployAppId)" appSecret="$(DeployAppSecret)" botId="$(BotName)" botSku=F0 newAppServicePlanName="$(BotName)" newWebAppName="$(BotName)-$(Build.BuildId)" groupName="$(BotName)-RG" groupLocation="westus" newAppServicePlanLocation="westus"

   git config --global user.name "GitPythonDeploymentUser"
   git config --global user.email GitPythonDeploymentUser@Pipeline.com
   git init
   git add .
   git commit -m "cibuildtest"
   git remote add azure https://$(AzureDeploymentUser):$(AzureDeploymentPassword)@$(BotName)-$(Build.BuildId).scm.azurewebsites.net:443/$(BotName)-$(Build.BuildId).git
   git push azure master
```

With this arm template:

using https://github.com/microsoft/BotFramework-FunctionalTests/blob/main/SkillsFunctionalTests/python/skill/deploymentTemplates/template-with-new-rg.json

**Comment by BruceHaley** [comment]
The Python sample bot deployment pipelines Eric refers to have been rock steady, passing now and passing continuously for the last month. They do not use container deploys. Is it the container deploys that are failing?
The pipelines: Sample-Py-CoreBot-Linux-Test https://fuselabs.visualstudio.com/SDK_v4/_build?definitionId=1054 
Sample-Py-EchoBot-Linux-Test https://fuselabs.visualstudio.com/SDK_v4/_build?definitionId=1053

**Comment by jwiley84** [comment]
I tested deploying yesterday with a simple echo-bot from the samples repo, an existing RG,  and a new App Service plan, and ran into the same issue while using the AZ cli: aiohttp was not installed.

**Comment by Virtual-Josh** [comment]
As an update the issue is being caused because the Python virtual environment is missing. The new Azure support engineer is working on reproing and resolving.

**Comment by Virtual-Josh** [comment]
Based on Azure data this issue has occurred in the past a number of times so I'm not the first to hit it. 

There's also now a work around for the issue:

- Go to the `App Service` and go to `Configuration`  
- Enter `SCM_DO_BUILD_DURING_DEPLOYMENT` as a new `Application Setting`  and set the value to `true`
- Go to `General settings` and enter `gunicorn --bind 0.0.0.0 --worker-class aiohttp.worker.GunicornWebWorker --timeout 600 app:APP` into the `Startup Command` field. 
- Save and restart the bot. You might need to redeploy to have it work.

**Comment by tracyboehrer** [comment]
> Based on Azure data this issue has occurred in the past a number of times so I'm not the first to hit it.
> 
> There's also now a work around for the issue:
> 
> * Go to the `App Service` and go to `Configuration`
> * Enter `SCM_DO_BUILD_DURING_DEPLOYMENT` as a new `Application Setting`  and set the value to `true`
> * Go to `General settings` and enter `gunicorn --bind 0.0.0.0 --worker-class aiohttp.worker.GunicornWebWorker --timeout 600 app:APP` into the `Startup Command` field.
> * Save and restart the bot. You might need to redeploy to have it work.

This is what the templates in the samples specify.   I gather this is no longer working during the deploy?

**Comment by Virtual-Josh** [comment]
Correct. This also isn't happening if you do a deployment via the Azure plugin in VS Code.

**Comment by BruceHaley** [comment]
All working now. The missing settings described in the workaround are being correctly created.
