### ISSUE TITLE
Proactive messages via skills are not received by the parent bot

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/botbuilder-python#1414]
Proactive messages aren't received by the parent bot when used via skills. The message is sent out, but there's something wrong somewhere. 

The same issue happened with the JS sdk, and the fix was to use the app id of the parent instead of the child. I tried the same thing here, but that didn't work.

**Comment by gabog** [comment]
Closing this one for now, not enough info to understand the issue but we can revisit once we por [WatefallSkillBot](https://github.com/microsoft/BotFramework-FunctionalTests/tree/main/Bots/DotNet/Skills/CodeFirst/WaterfallSkillBot) to Python
