### ISSUE TITLE
XCORS error in gov 

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/botbuilder-python#1421]
![image](https://user-images.githubusercontent.com/50158775/97142803-9b7c3b80-171e-11eb-987f-5545902386a6.png)

same issue is happening in [JS](https://github.com/microsoft/botbuilder-js/issues/2953)

**Comment by tracyboehrer** [comment]
@Virtual-Josh Can you provide steps to reproduce?

**Comment by Virtual-Josh** [comment]
I'm going to close this issue for now as Azure support is digging into the issue. It seems to be a bot service issue.
