### ISSUE TITLE
Port: Fix issues with ExpectReplies and Invoke in SkillDialog

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/botbuilder-python#1423]
While adding BufferedReplies, type of InvokeResponse should be added to TurnState:

```cs
                        if (activity.Type == ActivityTypesEx.InvokeResponse)
                        {
                            TurnState.Add(BotFrameworkAdapter.InvokeResponseKey, activity);
                        }
```

https://github.com/microsoft/botbuilder-dotnet/pull/4845

And, on the Skill Dialog side, only one InvokeResponse should be sent.

**Comment by gabog** [comment]
Hi @axelsrz, would you be able to address this one and fix it for the next R11 rc?

Thanks
