### ISSUE TITLE
PORT: Fix locale determination in confirm/choice prompts/inputs

### ISSUE THREAD

**Issue by v-kydela** [microsoft/botbuilder-python#1430]
Port https://github.com/microsoft/botbuilder-js/pull/2534 to Python

**Comment by tonyanziano** [comment]
@tracyboehrer does this still need to be ported to Python? If not, please close the issue. Thanks

**Comment by tracyboehrer** [comment]
@tonyanziano This just hasn't been schedule for a release yet.
