### ISSUE TITLE
channels.py is missing 3 channels

### ISSUE THREAD

**Issue by v-kydela** [microsoft/botbuilder-python#1438]
## Version
main

## Describe the bug
[channels.py](https://github.com/microsoft/botbuilder-python/blob/main/libraries/botframework-connector/botframework/connector/channels.py) is missing Direct Line Speech, Test, and Twilio. These should be added for parity with [.NET](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Connector/Channels.cs) and [Node](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botframework-schema/src/index.ts#L1911-L1939). Once these are added, they should be referenced in the appropriate places like [channel.py](https://github.com/microsoft/botbuilder-python/blob/main/libraries/botbuilder-dialogs/botbuilder/dialogs/choices/channel.py) and [test_adapter.py](https://github.com/microsoft/botbuilder-python/blob/main/libraries/botbuilder-core/botbuilder/core/adapters/test_adapter.py).

**Comment by tracyboehrer** [comment]
Check for parity with DotNet.  Could be others, or already corrected, since this issue was opened.

**Comment by gandiddi** [comment]
DirectLine and SMS (Twilio) channels are present, need to add test channel.
