### ISSUE TITLE
[PORT] Fix Cosmos nesting problem (#4973)

### ISSUE THREAD

**Issue by v-kydela** [microsoft/botbuilder-python#1440]
The changes in [Fix Cosmos nesting problem (#4973)](https://github.com/microsoft/botbuilder-dotnet/pull/4973) may need to be ported to maintain parity with `microsoft/botbuilder-dotnet`.

<blockquote>
Fixes #4755

## Description
Some customers experienced cryptic error messages when using Cosmos. We discovered that deeply nested data was the culprit, so I've added new error messages to help customers who encounter this problem in the future.

## Specific Changes

  - Two new tests have been added to CosmosDbPartitionStorageTests
  - The custom exception type BotStateException has been created
  - CosmosDbPartitionStorage checks the nesting depth when a Cosmos exception is thrown during a write operation

## Testing
Included
</blockquote>

Please review and, if necessary, port the changes.

**Comment by tonyanziano** [comment]
@tracyboehrer  do you know if this was ported to python or is necessary? If not necessary, can you please close the issue. Thanks.

**Comment by tracyboehrer** [comment]
@tonyanziano It is needed, but hasn't been scheduled for a release yet.
