### ISSUE TITLE
VSCode / Pylance complaints about type annotation issues the libraries

### ISSUE THREAD

**Issue by asdkant-ey** [microsoft/botbuilder-python#1458]
## Version
4.11

## Describe the bug
VSCode's pylance complained about this, the message was:
```
List expression not allowed in type annotation
  Use List[T] instead
```
## Screenshots
![image](https://user-images.githubusercontent.com/68709979/103297041-3838af00-49d6-11eb-9740-b52d7ed7f078.png)

## Additional context
I'll add a PR for the instance of this I've found, but a code scan of the whole repo for this issue would be a good idea.

**Comment by joshgummersall** [comment]
Thanks for submitting the PR! The Python codeowners will review it as soon as they are back from the holidays.

**Comment by tracyboehrer** [comment]
This issue will be closed when the linked PR is corrected and merged.  Currently, there is a build error during validation.
