### ISSUE TITLE
Django: Application Insights does not accept TelemetryProcessor or TelemetryClient

### ISSUE THREAD

**Issue by daveta** [microsoft/botbuilder-python#150]
[Low priority]
This is technically not our bug, but it's faster for us to implement and create a PR.

Currently, within the App Insights Django Middleware (no information on Flask yet), there's no way to pass in the Telemetry Client (or TelemetryProcessor).  Therefore, we can't override user_id/session_id/etc properties (with bot-specific properties) that get generated from App-Insights generated telemetry.

Given our current telemetry don't use this in reports, not super important.

**Comment by axelsrz** [comment]
Assigning this to @tsuwandy per chat with Dave, but no rush needed.

**Comment by daveta** [comment]
it's modifying the [Application Insights Django Middleware component](https://github.com/microsoft/ApplicationInsights-Python/blob/develop/applicationinsights/django/middleware.py).
More detail: This is about finding a way to add bot-specific properties (user_id/session_id/etc) to all events being logged through the Application Insights pipeline.
Being able to pass in a [TelemetryProcessor](https://github.com/microsoft/ApplicationInsights-Python/pull/166) to pass into the Django Middleware component might be an option.  

This will entail modifying the App Insights code and submitting a PR (with tests) to their repo.

**Comment by tsuwandy** [comment]
Application Insights SDK for Python is never supported and now the team is pivoting toward using OpenCensus Python, which will be GA end of Sept.  https://github.com/census-instrumentation/opencensus-python.

**Comment by cleemullins** [comment]
Per discussion w/ Dave & Axel & Scott, we are not prioritizing Django at this time.

**Comment by axelsrz** [comment]
closed as #336
