### ISSUE TITLE
Received Slack payloads are not processed properly

### ISSUE THREAD

**Issue by omid-jf** [microsoft/botbuilder-python#1548]
## Version
v4.11.0

## Describe the bug
When content received from Slack is in type _application/x-www-form-urlencoded_, a dictionary called _request_dict_ is created from the body using the _query_string_to_dictionary_ method of the _SlackHelper_ class. The resulting dictionary has one key called _payload_ and its value is a dictionary with several key-values ({"type": ..., "user": ..., etc.}).
Later, a _SlackPayload_ object is created from the key-values. However, the constructor of the _SlackPayload_ class gets the values of the nested dictionary without getting the value of first key. Therefore, everything turns to be None in that object.

## To Reproduce
1. Use the _60.slack-adapter_ sample.
2. Put a breakpoint in line 11 of botbuilder/adapters/slack/slack_payload.py and start debugging.
3. Use the /test command in Slack (requires registering the command in the Slack application).
4. In Slack, click on of the buttons sent from the bot.

## Expected behavior
The created _SlackPayload_ object should contain information about the Slack action.

## Screenshots
![ms_bot_bug](https://user-images.githubusercontent.com/3337135/108619904-3f33da80-73e5-11eb-8d8f-861f4889b98b.JPG)

**Comment by omid-jf** [comment]
## Another related bug:
Line 29 of the same file (slack_payload.py) has an incorrect syntax (check the screenshot below).
`if isinstance(message) is SlackMessage`
should be changed to:
`if isinstance(message, SlackMessage)`

![ms_bot_bug2](https://user-images.githubusercontent.com/3337135/108620454-90de6400-73e9-11eb-9298-844e973a55a5.JPG)

**Comment by congysu** [comment]
Thanks @axelsrz to take a look at this item.

**Comment by congysu** [comment]
@axelsrz could you please take a look at this one?  Thanks.

**Comment by axelsrz** [comment]
bringing @tracyboehrer into the loop

**Comment by tracyboehrer** [comment]
@omid-jf Thanks for reporting this.  I'll get setup to test and correct this, and get it into the next release.
