### ISSUE TITLE
Incorrect adal requirement in botframework-connector setup.py

### ISSUE THREAD

**Issue by cas--** [microsoft/botbuilder-python#1620]
## Version
botframework-connector 4.12.0

## Describe the bug
While looking into dependencies installed by botframework-connector I saw that deprecated **adal** in addition to **msal**. 

The _requirements.txt_ does not have this requirement but [setup.py does](https://github.com/microsoft/botbuilder-python/blob/293916fa96b147cf2cd0ef4726a2ddd0605b9155/libraries/botframework-connector/setup.py#L15)

I did a quick github search and no reference to adal and looks like it was replaced with msal here: https://github.com/microsoft/botbuilder-python/commit/5a622806f3d5b0e39d16fc3de948fe469ff81c8f

## To Reproduce
    pip install botframework-connector

## Expected behavior
No unneeded pip packages

**Comment by peterinnesmsft** [comment]
@tracyboehrer @axelsrz can you please take a look at the submitted PR and verify if we need any additional changes?
