### ISSUE TITLE
Pip install - aiohttp CVE update (v3.7.4) is incompatible with botbuilder 4.12.0 modules

### ISSUE THREAD

**Issue by james-flynn-ie** [microsoft/botbuilder-python#1621]
## Version
What package version of the SDK are you using: 4.12.0

## Describe the bug

Dependabot recommends upgrading aiohttp>=3.7.4, due to a CVE security vulnerability (https://github.com/advisories/GHSA-v6wp-4m6f-gcjg), but this package version returns an incompatibility error when run with botbuilder modules. I've since had to revert the dependency upgrade.

When running pip install with the updated package version and botbuilder modules v4.12.0 (See https://github.com/james-flynn-ie/covid-bot/blob/main/requirements.txt for module list), it returns these errors:

```python
ERROR: botbuilder-ai 4.12.0 has requirement aiohttp==3.6.2, but you'll have aiohttp 3.7.4 which is incompatible.
ERROR: botbuilder-integration-aiohttp 4.12.0 has requirement aiohttp==3.6.2, but you'll have aiohttp 3.7.4 which is incompatible.
```

## To Reproduce

1. Update aiohttp to 3.7.4 on any Python botbuilder project requirements.txt file (see https://github.com/james-flynn-ie/covid-bot/blob/main/requirements.txt for example)
2. Run `pip install -r requirements.txt`
3. Observe errors in console output.

## Expected behavior

Errors are not displayed that aiohttp==3.6.2 is a requirement.
Pip install successfully installs all dependencies and Bot Framework Python SDK apps run as expected.

**Comment by v-kydela** [comment]
@james-flynn-ie - Thank you for the report. Can you let us know what version of Python you're using?

@peterinnesmsft - How would you like the support team to assist with this?

**Comment by james-flynn-ie** [comment]
Thanks for your response, @v-kydela , I'm using pip 18.1

**Comment by v-kydela** [comment]
@james-flynn-ie - Thank you for that information, but I think the Python version is likely to end up being more important than the pip version. I presume you're using Python 3, but is it 3.7, 3.8, 3.9, etc.?

**Comment by james-flynn-ie** [comment]
> @james-flynn-ie - Thank you for that information, but I think the Python version is likely to end up being more important than the pip version. I presume you're using Python 3, but is it 3.7, 3.8, 3.9, etc.?

Hi @v-kydela , you're correct of course. Sorry, I misread what you were asking and was kinda wondering why Pip would be important. 😊

I'm using Py 3.6 at present, as later versions throw errors due to changes in asyncio reserved keywords https://tryexceptpass.org/article/asyncio-in-37/

**Comment by v-kydela** [comment]
@james-flynn-ie - Is that 3.6.8? 3.6.9? 3.6.10?

Also, can you reproduce this problem with any of the Bot Builder samples? I just tried the [echo bot sample](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/python/02.echo-bot) and I can't get the requirements to install with Python 3.6.8. There are problems with the cryptography package, etc. Did you encounter any such problems?

**Comment by james-flynn-ie** [comment]
Hi @v-kydela 

Yes, I have experienced some issues with authentication when running the bot locally through the emulator.

With regards to the pip install issue, the aiohttp version is set in the requirements.txt files for the libs, e.g.: https://github.com/microsoft/botbuilder-python/blob/885d3d11304aa3fedefee400378721c2c3e423bd/libraries/botbuilder-integration-aiohttp/requirements.txt#L4

I can go ahead and open a pull request updating them, but I'm not sure what your dev/test processes are like for verifying them?

**Comment by cas--** [comment]
@james-flynn-ie The next release will likely fix this since #1561 relaxed the aiohttp pinning

**Comment by james-flynn-ie** [comment]
Awesome thanks for update @cas-- 

Did we have an idea when this is likely to be released?

**Comment by v-kydela** [comment]
@james-flynn-ie - There should be a release this month but you can also try nightly builds: https://github.com/microsoft/botbuilder-python/blob/main/UsingTestPyPI.md

Does this resolve your issue?

**Comment by james-flynn-ie** [comment]
Yes, that should be fine. Thanks for your help, @v-kydela and @cas-- 👍

**Comment by cas--** [comment]
@v-kydela This is not fixed since botbuilder-integration-aiohttp lists the dependency as [`"aiohttp~=3.6.2"`](https://github.com/microsoft/botbuilder-python/blob/4003d713beb8fb986a01cfd11632eabc65858618/libraries/botbuilder-integration-aiohttp/setup.py#L13) instead of `"aiohttp>=3.6.2,<3.8.0"`

Error log: 
```
There are incompatible versions in the resolved dependencies:
  aiohttp>=3.7.4 (from -r requirements.in (line 1))
  aiohttp~=3.6.2 (from botbuilder-integration-aiohttp==4.13.0->-r requirements.in (line 2))
```
