### ISSUE TITLE
Facing Issue while hitting QnA Service using botbuilder-ai	 

### ISSUE THREAD

**Issue by dhruv2103** [microsoft/botbuilder-python#1628]
## Version
4.12.0

## Describe the bug
While using botbuilder-ai package for hitting QnA service for an answer. I am getting this error:
![image](https://user-images.githubusercontent.com/36305262/113971156-d8b03200-9855-11eb-81a2-58671b2f1058.png)

I checked through site-packages and also tried hitting QnA using postman. while going through site-packages, I also printed request objects and responses which I am getting. I am getting HTTP code 401(Unauthorized client). but for the same 'knowledge_id' and 'endponit_key', I am getting the right answer without any error in postman.

I checked the request object of both and got to know that just by removing "EndpointKey" from "Authorization" token in header, the problem can be solved.

## To Reproduce
1. Download [sample QnA bot code](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/python/11.qnamaker)
2. create a knowledge base using [qna service](https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/quickstarts/create-publish-knowledge-base?tabs=v2)
3. copy & paste knowledge base details in config.py
![image](https://user-images.githubusercontent.com/36305262/113973191-86711000-9859-11eb-9354-4945ce5edc17.png)
4. Run app.py & test it using [Bot Framework Emulator](https://github.com/microsoft/BotFramework-Emulator)

## Expected behavior
It should return answers to a given question from the knowledge base.

## Screenshots
![image](https://user-images.githubusercontent.com/36305262/113971156-d8b03200-9855-11eb-81a2-58671b2f1058.png)

## Additional context
I have resolved this error using following steps:
1. Go to 'venv/lib/python3.7/site-packages/botbuilder/ai/qna/utils/http_request_utils.py'
2. in header object of '_get_headers' method, replace,
`"Authorization": f"EndpointKey {endpoint.endpoint_key}"
  "Ocp-Apim-Subscription-Key": f"EndpointKey {endpoint.endpoint_key}"`
with
`"Authorization": f"{endpoint.endpoint_key}",
  "Ocp-Apim-Subscription-Key": f"{endpoint.endpoint_key}"`
4. It is working for me without any error on my local.

but I have to deploy it on App Service. while deploying it on App Service, I am facing the same issue. I was able to make changes on my local and able to run it without error. but on app service, I couldn't.

**Comment by Zerryth** [comment]
@dhruv2103 - I wasn't able to reproduce the error you got, and was able to run sample 11.qnamaker with a KB without issue.

✔️ 
![image](https://user-images.githubusercontent.com/35248895/114079972-a9062780-985f-11eb-8e00-07248b2e3dff.png)

___

Could you also clarify what's happening as well, as you mention
>  I am getting HTTP code 401(Unauthorized client).

And provide a screen shot of the stack trace, but there is no such 401 in the logs there. Please provide the full error or perhaps more detail as to exact steps taken to get there.

___

### Some things to note

* If you include appId and password in your bot's config, be sure to also include them in emulator as well
    * *config.py*
       * ![image](https://user-images.githubusercontent.com/35248895/114080516-56793b00-9860-11eb-8dd8-137dcbb5890a.png)

* *don't forget credentials here (emulator)*
       * ![image](https://user-images.githubusercontent.com/35248895/114080716-8c1e2400-9860-11eb-9f76-3997989234df.png)

**Comment by Zerryth** [comment]
Oh, additionally I just noticed something. Could you make sure to update to the latest python botbuilder packages? We still need to bump the versions in samples to the latest

```
botbuilder-integration-aiohttp>=4.12.0
botbuilder-ai>=4.12.0
```

**Comment by dhruv2103** [comment]
@Zerryth When I got that "KeyError: Answer" Error on the console. I went and take a look in site-packages. I printed out the request-payload, header, and response that I am getting by hitting QnA Service. There I got to know that while hitting QnA Service, I am getting HTTP code 401(Unauthorized client).

_<span style="color:red">Note: On console, I am getting "KeyError: Answer" error only.</span>_
![image](https://user-images.githubusercontent.com/36305262/114134025-9dc8ff80-9924-11eb-94c9-34fc1485087c.png)

but when I printed out all the details, I got to know that It is because I am getting an error in the response and it can't find the "Answer" attribute in the response object.
![image](https://user-images.githubusercontent.com/36305262/114131917-0c0bc300-9921-11eb-8238-dee5fedbc916.png)

Here, If you'll look at "Authorization" and "Ocp-Apim-Subscription-Key" in the header, There is "EndpointKey" added before my key. but while providing QnA configurations, I am providing these details as following:

![image](https://user-images.githubusercontent.com/36305262/114132394-e59a5780-9921-11eb-8f10-a9714fc1f0b9.png)

I am not adding that "EndpointKey" while providing configurations. It is being added in the [http_request_utils.py](https://github.com/microsoft/botbuilder-python/blob/13a9b096424e355bb69dca730c75965f8064eeb9/libraries/botbuilder-ai/botbuilder/ai/qna/utils/http_request_utils.py) file.

![image](https://user-images.githubusercontent.com/36305262/114132689-7709c980-9922-11eb-9b66-5e52334eaa3d.png)

What I am saying is that if I remove this "EndpointKey" from "Authorization" and "Ocp-Apim-Subscription-Key". It works fine without any error. I did the same for my local machine. but while deploying it on Azure App Service, It does all these installations by itself and won't allow me to make any changes too.

Yeah, I am installing these requirements:
`aiohttp `
`gunicorn`
`botbuilder-integration-aiohttp>=4.12.0`
`botbuilder-ai>=4.12.0`
`botbuilder-core>=4.12.0`
`botbuilder-dialogs>=4.12.0`
`datatypes-date-time>=1.0.0.a2`

and "MicrosoftAppId" and "MicrosoftAppPassword" are also right and adding it in the emulator. I am able to authenticate my bot using this.

**Comment by Zerryth** [comment]
Thanks for the additional detail. 

Hmm...it looks like you're using v5 preview version of the QnAMaker API, which I need to check if the SDK is even equipped to handle that yet (generally we don't integrate preview versions of dependencies into the framework, waiting for it to GA first though)

I'll investigate v5 preview version some more, but could I ask you if you're actually able to get a successful request using Postman and the hostname you have there? Here's the [API documentation on Generate Answer](https://docs.microsoft.com/en-us/rest/api/cognitiveservices-qnamaker/qnamaker5.0preview1/knowledgebase/generateanswer) for v5-preview. 

>HTTP
> `POST {Endpoint}/qnamaker/v5.0-preview.1/knowledgebases/{kbId}/generateAnswer`
![image](https://user-images.githubusercontent.com/35248895/114239778-5dc14700-993b-11eb-9520-3c68cd1bda9a.png)

Your hostname should use the "`qnamaker-resource-name`", and I see in your config you have this as your hostname
`https://australiaeast.api.cognitive.microsoft.com/qnamaker/v5.0-preview.1`

Is `australiaeast.api.cognitive.microsoft.com` actually correct?
The qnamaker-resource-name should in this case be the `Custom domain name` of your QnA Maker cognitive service resource in Azure Portal

![image](https://user-images.githubusercontent.com/35248895/114240647-b0e7c980-993c-11eb-957f-63f89d5a49e8.png)

**Comment by Zerryth** [comment]
## V5
Ok, I tried querying the v5.0-preview.1 GenerateAnswer API of QnAMaker, and I get 401 directly from both Postman and within the "[REST API Try It](https://docs.microsoft.com/en-us/rest/api/cognitiveservices-qnamaker/qnamaker5.0preview1/knowledgebase/create#code-try-0)" section of the Generate Answer API, and it is returning 400.

*Request*
```
POST https://<qnamaker-resource-name>.cognitiveservices.azure.com/qnamaker/v5.0-preview.1/knowledgebases/a9xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx18/generateAnswer
Content-type: application/json
Ocp-apim-subscription-key: abe2xxxxxxxxxxxxxxxxxxxxxxxx17c4
```
* note: the value of `Ocp-apim-subscription-key` is one of the keys from the actual QnA Maker cognitive service that you find in the Azure portal
   * ![image](https://user-images.githubusercontent.com/35248895/114250018-21004a80-9951-11eb-8d28-b77ba5c1c94e.png)
 

*Response*
```
{
  "error": {
    "code": "BadArgument",
    "message": "Invalid input. See details.",
    "details": [
      {
        "code": "ValidationFailure",
        "message": "GenerateAnswer not supported for this kind.",
        "target": "GenerateAnswer"
      }
    ]
  }
}
```
Hmm...seems like either documentation on v5 qna API is either out of date or the API itself is broken.

Additionally, I would safely say that currently while v5 of QnAMaker API is in preview that the SDK doesn't support it yet, because for our POST requests to Generate Answer API, we are *not* expecting the key from Azure portal, but instead they EndpointKey you see inside the Publish settings inside qnamaker.ai. (Again, the SDK generally doesn't integrate with preview APIs as well, given how they could change and then break us)
___
## Use V4

If using the `QnAMaker` class in the SDK, please use v4 credentials instead of v5-preview. Test that you have all the correct credentials first via Postman, just so you know for sure you've grabbed the correct keys for the request, then plug them into your bot.

All the information you need to make a request to v4 Generate Answer API is nicely in one place directly in the qnamaker.ai portal
![image](https://user-images.githubusercontent.com/35248895/114250230-e21ec480-9951-11eb-9818-ad15d3e9b7da.png)

* note how here QnAMaker expects the `Authorization` header and doesn't care for the `Ocp-apim-subscription-key` header (we could omit this from the SDK as from testing, I found that this was unnecessary)
* The value of `Authorization` is right there in qnamaker.ai portal right after `Authorization` -- `EndpointKey ...`
* Additionally we want the hostname that includes "`azurewebsites.net`" in it for v4 API

*Request*
```
POST https://xxxxxxxxxxxx.azurewebsites.net/qnamaker/knowledgebases/a9xxxxxx-xxxx-xxxx-xxxx-xxxxxxxx1918/generateAnswer
Content-type: application/json
Authorization: EndpointKey 5ef2xxxx-xxxx-xxxx-xxxx-xxxxxxxx08cd
```

*Response*
```
{
    "answers": [
        {
            "questions": [
                "hi"
            ],
            "answer": "salutations",
            "score": 100.0,
            "id": 1,
            "source": "Editorial",
            "isDocumentText": false,
            "metadata": [],
            "context": {
                "isContextOnly": false,
                "prompts": []
            }
        }
    ],
    "activeLearningEnabled": false
}
```
### In your bot config

Copying what I wrote earlier:
> QNA_KNOWLEDGEBASE_ID = os.environ.get("QnAKnowledgebaseId", "7b1xxxx-xxxx-xxxx-xxxx-xxxxxxxx511e")
> QNA_ENDPOINT_KEY = os.environ.get("QnAEndpointKey", "433xxxxx-xxxx-xxxx-xxxx-xxxxxxxx4379")
> QNA_ENDPOINT_HOST = os.environ.get("QnAEndpointHostName", "https://xxxxxxxxxx.azurewebsites.net/qnamaker")

* endpoint key: make sure the key you use is the one directly from qnamaker.ai portal > settings
* host: use endpoint that includes `https://qnamaker-resource-name.`**`azurewebsites.net`**

**Comment by Zerryth** [comment]
**More info regarding v5-preview investigation:**

When trying to use the EndpointKey value instead of one of the 2 keys inside of the QnA Maker Azure resource that `Ocp-apim-subscription-key` is expecting, you get 401 error that also cautions you to use the correct keys for corresponding API 

```
{"error":{"code":"401","message":"Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource."}}
```

That is, when following the v5 API doc, the only header it wants is `Ocp-apim-subscription-key` and not `Authorization` at all (yet for every scenario in the SDK, we always send `Authorization` header still)

___
Giving `Ocp-apim-subscription-key` one of the keys from QnA Maker cognitive service resource in Azure portal, it does get you passed the 401 unauthorized error, but we still land at `400 GenerateAnswer not supported for this kind.` error

**Comment by dhruv2103** [comment]
@Zerryth

Thank you for this information...

I will try v4 and will get back if I face any error.

meanwhile, I checked my azure qna resource. my endpoint is [https://australiaeast.api.cognitive.microsoft.com](https://australiaeast.api.cognitive.microsoft.com) only.
![1](https://user-images.githubusercontent.com/36305262/114255012-50a26780-99d0-11eb-9582-6c3f17e8b358.png)

is it because of QnAMaker v2? there is this custom domain option also... I haven't tried it, but I will.

**Comment by dhruv2103** [comment]
I created a custom domain. but it is not as you showed in your response. it is like: [https://osight-qna.cognitiveservices.azure.com](https://osight-qna.cognitiveservices.azure.com/)

apart, I also explored KB v4. I am trying to create a knowledge base with that version. but it is giving an error.

![image](https://user-images.githubusercontent.com/36305262/114255219-9b70af00-99d1-11eb-8775-f9a05f89db5a.png)

looking at this response. I am convinced that it is because of QnAMaker v2. isn't it?

let me just create QnAMaker with version 1 and check whether it is working or not.

**Comment by dhruv2103** [comment]
@Zerryth 

Hi, I am trying to create QnAMaker v1. but unable to create. can show me the steps, how you created QnAMaker and Knowledge-base using API v4?

**Comment by Zerryth** [comment]
@dhruv2103 Just followed the instructions in the [QnA Quickstart doc](https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/quickstarts/create-publish-knowledge-base?tabs=v1)

So to clarify, when you go to qnamaker.ai, sign in, click on your knowledge base, then click on Settings tab and scroll to the bottom, you don't see anything under Deployment Details? Or if you haven't published the KB yet, go to Publish tab, publish, and it should still get you the information you need to query v4 Generate Answer API

**Comment by Zerryth** [comment]
Additionally, just linking this here for anyone who looks at this thread. Regarding QnA Maker v5 API, it looks like we have an issue tracking to bring support to it here: https://github.com/microsoft/botbuilder-dotnet/issues/5063. It has yet to be implemented, however you can check back at that issue if interested in updates regarding its availability for use with the BF SDK

**Comment by dhruv2103** [comment]
@Zerryth 
Thanks... I will try this out and will get back to you...

**Comment by dhruv2103** [comment]
Hey, Thanks...! I tried with v4.0. It is working properly... Thank You for your help...!

**Comment by dhruv2103** [comment]
@Zerryth Hi, Thanks for your help with QnA. It is working now. but, From the last 2 days, I am facing another error. 

It is not related to this... but I think you might help me with this or get me someone who can.....

So, as it is working now on my local. I want to publish it on azure. I did follow the steps shown in [Bot Framework SDK Documentation](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-deploy-basic-bot?view=azure-bot-service-4.0&tabs=python).

1. I registered for a new App for OAuth.
2. Deployed ARM Template. (using the same ARM template given with [QnA Bot Example](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/python/11.qnamaker))
3. and Pushed my code. (Note: I did make sure that app.py and requirements.txt in the same location).

I am successfully able to create the app-service plan, app service, and bot channel registration. 
I am also able to deploy my code using the given commands on [Bot Framework SDK Documentation](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-deploy-basic-bot?view=azure-bot-service-4.0&tabs=python)

The error which I am facing is that while deployment it is showing an error for "No module found named 'aiohttp'":
![image](https://user-images.githubusercontent.com/36305262/115656822-7ece6280-a353-11eb-84ac-3219c126c331.png)

while I did have 'aiohttp' in my requirements.txt.
![image](https://user-images.githubusercontent.com/36305262/115656974-bfc67700-a353-11eb-9562-2015f882b7f8.png)

I looked online. but everywhere, I found similar steps which I am following. I also looked at ["hello world!" app service deployment](https://docs.microsoft.com/en-us/azure/app-service/quickstart-python?tabs=bash) using python.
but it is not helping.

I found the same issue on Github at [ModuleNotFoundError: No module named 'aiohttp'](https://github.com/Azure/azure-functions-python-worker/issues/713)

but I didn't find any solution there.

can you pls help me find the solution for this?

**Comment by Zerryth** [comment]
@dhruv2103 please open a new GH issue, so it goes through the process of being assigned to the right people

**Comment by dhruv2103** [comment]
Ohk... Thanks! I have created new GH Issue.
