### ISSUE TITLE
Expose prompts in botbuilder.dialogs

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-python#166]
In JS and C# users aren't required to go into the prompts folder in the libraries to use the prompts classes.

```js
import prompts from 'botbuilder-dialogs';
// Then use TextPrompt
```

```cs
using Microsoft.Bot.Builder.Dialogs.Prompts;
```

They're either exposed through the namespace or at the top-level index.js.

**Describe the solution you'd like**
Python should do the same, unless it would prevent traditional Python developers from being able to do the normal/expected `from botbuilder.dialogs.prompts import TextPrompt` syntax.

More specifically, it's unclear if doing the following will result in a collision if the `prompts` are exposed through `botbuilder.dialogs`:

```py
from botbuilder.dialogs import *
from botbuilder.dialogs.prompts import *
# Or from botbuilder.dialogs.prompts import TextPrompt
```

[enhancement]

**Comment by axelsrz** [comment]
Fixed in #181
