### ISSUE TITLE
BotFrameworkAdapter.create_conversation overrides parameters.channel_data

### ISSUE THREAD

**Issue by yosshy** [microsoft/botbuilder-python#1665]
## Version
4.13

## Describe the bug
A Teams bot using BotFrameworkAdapter can't create conversation in a team channel. turn_context.adapter.create_conversation() raises a parameter error of HTTP request.

## To Reproduce
1. Deploy a bot using BotFrameworkAdapter and turn_context.adapter.create_conversation() method to create a conversation in a team channel. To do it, conversation_parameters argument of create_conversation() must have channel_data attribute that has information of the channel to use.
2. Show the logs of the bot. If you use Azure, Log-in to the Azure portal with a web browser, click "app service", click the bot app and click Log Stream.
3. Log-in Teams.
4. Make the bot creating a conversation in a team channel.
5. See an error.
6. Confirm the error logs in the log window you opened at step 2.

## Expected behavior
A conversation will be created without any error.

## Screenshots
No.

## Additional context
No.

## Additional Information
parameters.channel_data looks overridden in create_conversation() below:
https://github.com/microsoft/botbuilder-python/blob/main/libraries/botbuilder-core/botbuilder/core/bot_framework_adapter.py#L369

IMO, it should be:
```
if parameters.channel_data is None:
    parameters.channel_data = {}
parameters.channel_data["tenant"] = {"tenantId": reference.conversation.tenant_id}
```

**Comment by v-kydela** [comment]
Thank you for the report, @yosshy 

Can you provide some code to help us reproduce the issue? Are you following a sample, perhaps?

Also, are you able to reproduce this problem with a local bot or only with a deployed bot?

**Comment by yosshy** [comment]
@v-kydela thank you for your reply. I'm not following a sample but creating a new bot for our purpose. Currently, I can't provide our code soon.

If "a local bot" means one running with emulator, we can't reproduce it because it is not for a team channel but for 1:1 chat. So, we can do it only with a deployed one.

**Comment by v-kydela** [comment]
Hi @yosshy 

While Emulator is useful for testing local bots, Emulator is just another client and does not define where the bot is running. You can test local bots on Emulator or Teams, and you can test deployed bots on Emulator or Teams.

If you're unfamiliar with tunneling, please refer to this documentation: https://docs.microsoft.com/azure/bot-service/bot-service-debug-channel-ngrok

**Comment by yosshy** [comment]
Hi @v-kydela ,

Thank you for your description about local bots. I have no local environment for a local bot but I'll prepare it soon.

**Comment by v-kydela** [comment]
@yosshy - Have you prepared a local environment yet?

**Comment by v-kydela** [comment]
@cleemullins - I think this is a legitimate bug rather than a support issue. A suggested fix was provided in the original post, but I think it should be applied to the other SDK's as well. Can this be escalated?

**Comment by v-kydela** [comment]
@yosshy - As a workaround, you can bypass the adapter by calling `connector_client.conversations.create_conversation` directly as seen in [this sample](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/python/58.teams-start-thread-in-channel/bots/teams_start_thread_in_channel.py#L35)

@EricDahlvang - To reproduce this bug, you need to call `adapter.create_conversation` as described in the original repro steps. The sample can be modified to do so.

**Comment by johnataylor** [comment]
@axelsrz can you take a look and confirm this is a bug in the product.

**Comment by axelsrz** [comment]
We will add this bug to our current iteration to provide a fix.

**Comment by tracyboehrer** [comment]
To those that have reproduced this error, what data is being put into ConversationParameters.channel_data?  Specifically, how does that differ from sample 57.teams-conversation-bot, which doesn't populate channel_data at all?  What I'm trying to chase down is whether we still have to add tenant id to channel_data.
