### ISSUE TITLE
[Dialogs] InputHint is hardcoded for AttachmentPrompt as expecting_input

### ISSUE THREAD

**Issue by denscollo** [microsoft/botbuilder-python#1670]
## Version
4.12.0

## Describe the bug
In the [AttachmentPrompt](https://github.com/microsoft/botbuilder-python/blame/main/libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/attachment_prompt.py) class, the **prompt.input_hint** is set as [expecting_input](https://github.com/microsoft/botbuilder-python/blame/main/libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/attachment_prompt.py#L45) replacing any value the user could set.
This behavior is not present in either .NET or JS SDKs.

## To Reproduce
1. Using the sample: [05.multi-turn-prompt](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/python/05.multi-turn-prompt):
    - Open [dialogs/user_profile_dialog.py](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/python/05.multi-turn-prompt/dialogs/user_profile_dialog.py) file.
    - Add the following line to the imports section `from botbuilder.schema import InputHints`.
    - Update picture_step method adding `input_hint=InputHints.accepting_input` to the message as can be seen below:
![image](https://user-images.githubusercontent.com/44245136/115744805-45a0ed00-a369-11eb-9eb1-6d86e9d73a26.png)
    - Save the changes.
    - Open the console in the bots folder and run the following commands:
        -  python -m pip install -r requirements.txt
        - python app.py

2. Open BotFramework Emulator and connect to your bot.
3. Follow the dialog flow until the profile picture step.
4. See the activity in the Inspection panel and check the value of the inputHint property.
![image](https://user-images.githubusercontent.com/44245136/115744882-56516300-a369-11eb-837b-833dcce1bec7.png)

## Expected behavior
The bot should send the activity with the inputHint property that was set for the message in the prompt options.

**Comment by tdurnford** [comment]
@axelsrz Can you take a look at this?

**Comment by axelsrz** [comment]
@tdurnford I'm removing Bot Services and customer-reported tags as Denise is from southworks team
