### ISSUE TITLE
BotFrameworkAdapter.process_activity_with_identity calls serialize() on dict

### ISSUE THREAD

**Issue by jooste** [microsoft/botbuilder-python#1672]
## Version
4.13.0

## Describe the bug
When running, e.g., the [fetch task](https://github.com/microsoft/botbuilder-python/tree/main/tests/teams/scenarios/action-based-messaging-extension-fetch-task) example, an exception is raised when `on_teams_messaging_extension_fetch_task` is called. The problem is that in `bot_framework_adapter.py` on line 515, `serialize()` is called on `invoke_response.value.body`, which is a python dict.

## To Reproduce
1. run the above-mentioned example and add to teams
2. Trigger bot's 'create card' message extension
3. A dialog is shown with an error, and an exception is raised in the bot code.

## Expected behavior
Expected behavior is that the 'Create Card' example dialog is shown instead of an error. A fix to this error could for instance be to change line 515 in `bot_framework_adapter.py` to:
```python
return InvokeResponse(
                status=invoke_response.value.status,
                body=invoke_response.value.body   # line 515
```

**Comment by tdurnford** [comment]
@axelsrz Can you take a look at ths?

**Comment by axelsrz** [comment]
@jooste thanks for submitting this, we will investigate and provide a fix in our next release if found necessary.

**Comment by ninggao** [comment]
@axelsrz  any updates on this issue?

**Comment by johnataylor** [comment]
@jooste thanks for summitting this issue. We'll prioritize fixing this in the next milestone.
