### ISSUE TITLE
Python Twilio Adapter for Bot Framework

### ISSUE THREAD

**Issue by ruchitaharsora** [microsoft/botbuilder-python#1723]
### Use this [query](https://github.com/Microsoft/botbuilder-python/issues?q=is%3Aissue+is%3Aopen++label%3Afeature-request+) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ruchitaharsora** [comment]
I am trying to build a chatbot on Microsoft Bot Framework and integrate it with Twilio so that my target audience can ping the number and interact with my bot.

But it seems there is not in-built adapter for Twilio like I see for slack in botbuilder-python repository.

Could you help me here?
@tracyboehrer @mdrichardson

**Comment by tracyboehrer** [comment]
@ruchitaharsora Thanks for your interest in Bot Framework and the Twilio adapter.  Unfortunately, the Twilio adapter is not on our immediate timeline to implement.  However, if we were to it would likely be a port of the [TwilioAdapter in the Dotnet](https://github.com/microsoft/botbuilder-dotnet/tree/main/libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio) repo.  It appears the [client from Twilio](https://www.twilio.com/docs/libraries/python/custom-http-clients-python#:~:text=Custom%20HTTP%20Clients%20for%20the%20Twilio%20Python%20Helper,3%20Call%20Twilio%20through%20the%20proxy%20server.%20) is similar.
