### ISSUE TITLE
Pylint Score 5.18/10

### ISSUE THREAD

**Issue by dciborow** [microsoft/botbuilder-python#173]
## Version
Master Branch

## Describe the bug
Pylint is not being used for code analysis. The current rating for the published code is 5.18/10, and calls out specific issues with the format and static code analysis that should be addressed. 

## To Reproduce
pip install pylint
pylint libraries

## Expected behavior
pylint score should be 10/10. If certain rules need to be bent for very specific reasons a pylint config file should be provided. 

## Screenshots
![image](https://user-images.githubusercontent.com/9027725/57642971-95c08380-7586-11e9-86a6-3636fba45f97.png)

## Additional context

[bug]

**Comment by axelsrz** [comment]
This issue was addressed in the following PRs:

#259, #266, #267, #268, #271, #272, #274, #275
