### ISSUE TITLE
[BUG]: Returning MessagingExtensionActionResponse giving serializer error in python

### ISSUE THREAD

**Issue by moshfiqrony** [microsoft/botbuilder-python#1759]
## Sample information
1. Sample type: [https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/python/53.teams-messaging-extensions-action-preview]
2. Sample language: [python]
3. Sample name: 53.teams-messaging-extensions-action-preview

## Describe the bug
I am trying to run the sample. When I run it and invoke a Messaging Extension, the request passed to the ```/api/messages``` endpoint and the ```on_teams_messaging_extension_fetch_task``` function gets called. The cards and the task gets created successfully. When the function return a ```MessagingExtensionActionResponse``` type response it gives an error like 
> 'dict' object has no attribute 'serialize'

## To Reproduce
1. Go to https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/python/53.teams-messaging-extensions-action-preview
2. Clone it and run it By reading the Readme
3. Try to invoke a Messaging extension
4. To see the error see error wrap the code inside ```messages``` function in the **app.py** file in a ```try except``` block

## Expected behavior
It should open a modal with an Adaptive card

## Screenshots
![image](https://user-images.githubusercontent.com/26689488/123251583-2eb77c00-d50d-11eb-8aa5-3be4f5416d95.png)

## Additional context
I try the same adaptive card in the JSON approach and it worked. But not with the bot-builder package. Which means when I return a Task JSON to the request it works. Which means My card code is working fine. It is creating the error when I am return from the function. I suppose it is an error of the package.

**Comment by stevengum** [comment]
This looks like a bug in the SDK, we'll ship this bug fix in the R15 release of the SDK which is due later this summer.

**Comment by moshfiqrony** [comment]
Thank you so much. I also assumed that this is a bug in the SDK because I tried all the possible approaches like JSON response. The JSON response worked for me but not the SDK one. So I was a bit sure that the problem is in the SDK.

**Comment by tracyboehrer** [comment]
This is probably related to https://github.com/microsoft/botbuilder-python/pull/1726/files, which is fixed in R14.  We will need to verify.

**Comment by moshfiqrony** [comment]
@tracyboehrer Thanks, I just checked and I think yes this is the solve. But how I would get the updated package?

**Comment by moshfiqrony** [comment]
I meant The latest version is 4.13.0 and it has the old code. How can I get the fixed code in the package and install it using pip

**Comment by moshfiqrony** [comment]
version 14 is released and the problem was also solved. Thanks
