### ISSUE TITLE
Port of OAuth functionality

### ISSUE THREAD

**Issue by axelsrz** [microsoft/botbuilder-python#183]
Changes in BotFrameworkAdapter:

- get_user_token
- get_oauth_sign_in_link
- sign_out_user
- get_token_status
- get_aad_tokens
- create_oauth_api_client
- get_app_credentials
- emulateOAuthCards
- *createTokenApiClient
- *oauthApiUrl
- *checkEmulatingOAuthCards
- *createContext

Classes that need porting:

- InvokeResponse
- UserTokenProvider (ABC)

**Comment by mdrichardson** [comment]
SDK will also need `oauth_prompt`. Not sure if that needed a separate issue or not.
