### ISSUE TITLE
Carousel not rendering adaptive cards in full width

### ISSUE THREAD

**Issue by RobinVds** [microsoft/botbuilder-python#1843]
## Version
botbuilder-ai==4.14.0
botbuilder-azure==4.14.0
botbuilder-core==4.14.0
botbuilder-dialogs==16
botbuilder-integration-aiohttp==4.14.0
botbuilder-schema==4.14.0
botbuilder-testing==4.14.0
botframework-connector==4.14.0
botframework-streaming==4.14.0

## Describe the bug
When I render my adaptive cards in a carousel the cards are decreased in width. When I try to use msteam { "width": "full"}, nothing changes.

## To Reproduce
Render adaptive cards in a carousel in the web app.

## Expected behavior
The cards in the carousel have the same width as when rendered outside of the carousel.
## Screenshots
![image](https://user-images.githubusercontent.com/35403078/144264054-2065dfe5-54f9-4707-a45f-a394596d8145.png)

## Additional context
Issue seems to be ok in desktop app

**Comment by axelsrz** [comment]
Hello @RobinVds could you confirm if you are experiencing this in Teams (web) or in a regular webchat app?

**Comment by RobinVds** [comment]
Until yesterday I was only experiencing this in the web client. Today it suddenly is the same for both the webclient as the normal teams app (downloaded).

So I'm experiencing it in the teams web client and the teams desktop app.

**Comment by axelsrz** [comment]
Hello @clearab this looks like a teams rendering issue, could you chime in?

**Comment by clearab** [comment]
I've reached out to them. @RobinVds for future reference please use one of the methods outlined here for Teams-specific issues in the future: https://docs.microsoft.com/en-us/microsoftteams/platform/feedback

**Comment by RobinVds** [comment]
@clearab thanks for pointing me to that page. I expected it to be an issue related to python. If I understood your message correctly you have already created an issue somewhere for this? If so, is there a way for me to track this?

**Comment by clearab** [comment]
The Teams group is currently investigating - either they or I will follow up on this thread when we have a more concrete answer.

**Comment by RobinVds** [comment]
@clearab do you think I could get soem kind of indication if this is going to be a matter of days/weeks/months/... as we are using the carousel in our production app and it is just not presentable to clients in this way.

**Comment by clearab** [comment]
The Teams group have repro'd the issue, and are working on solutions. I can only provide a rough estimate for a fix currently - the global roll-out of a solution should be sometime in Q1 of 2022.

**Comment by Meghana-MSFT** [comment]
This issue has been fixed and we have verified the fix. Attaching a screenshot of carousel cards with and without full width. Could you please check once and confirm the fix?

![image](https://user-images.githubusercontent.com/81138249/161036134-c0ea1e8e-cf18-4e3f-9d61-72368dad297b.png)
