### ISSUE TITLE
German language is not appropiate used when using Confirmprompts

### ISSUE THREAD

**Issue by PascalHessler** [microsoft/botbuilder-python#1882]
### The Issue
I am building a chatbot for german users. I am sending the local "de-de" as user, and can confirm this actual arrives the bot. When i want to use  Confirmprompts the bot returns Yes and No and not "Ja" "Nein". 
### The Solution
After a lot of digging, I found the underlying cause and a fix. The culture model does not actually recognices German (de-de) as supported language, and thus switches to the default (english). But in the prompt_culture_models.py German actualy exists and ther is a todo "# TODO: Replace with Culture.German after Recognizers-Text package updates." Which I looked up and the Recognizers-Text package sis already updated :) . Still this is not the real issue. 

The reason is that german is not listed in the supported cultures function. I simply added it and every thing works fine. 

`    @classmethod
    def get_supported_cultures(cls) -> List[PromptCultureModel]:
        """
        Gets a list of the supported culture models.
        """
        return [
            cls.Chinese,
            cls.German,
            cls.Dutch,
            cls.English,
            cls.French,
            cls.Italian,
            cls.Japanese,
            cls.Korean,
            cls.Portuguese,
            cls.Spanish,
            cls.Turkish,
        ]`

**Comment by ramfattah** [comment]
Hi @PascalHessler -- thanks, looking into this issue.

**Comment by msomanathan** [comment]
@PascalHessler There is a PR which will fix this issue. Thanks, @ramfattah for the PR!
