### ISSUE TITLE
ConversationsOperations.get_conversations not supported?

### ISSUE THREAD

**Issue by AlmogCohen** [microsoft/botbuilder-python#190]
## Version
`4.4.0b1`

## Describe the bug
Any call to `ConversationsOperations.get_conversations` returns HTTP request with status `405` and `b'{"message":"The requested resource does not support http method \'GET\'."}'`

## Expected behavior
I hope it would work and return past conversations. Unfortunately I'm not even it _should_ work as it is missing from the supported API calls listed [here](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-3.0#conversation-operations).

If supported, some fix. If not, remove the method from the SDK.

## Screenshots

https://cl.ly/a1bdaf

![Screenshot](https://cl.ly/a1bdaf/download/Image%202019-05-24%20at%205.00.19%20PM.png)

**Comment by v-kydela** [comment]
@AlmogCohen - What channel are you using?

**Comment by AlmogCohen** [comment]
Microsoft Teams

**Comment by v-kydela** [comment]
Teams doesn't support the "get conversations" API.

If you're interested the API is documented in the SDK reference for .NET and Node:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.connector.conversationsextensions.getconversationsasync
https://docs.microsoft.com/en-us/javascript/api/botframework-connector/conversations?view=botbuilder-ts-latest#getconversations-conversationsgetconversationsoptionalparams-

I've raised an issue about the missing REST API documentation: https://github.com/MicrosoftDocs/bot-docs/issues/1179
