### ISSUE TITLE
Add user-assigned managed identity for Python SDK 🙏🏻

### ISSUE THREAD

**Issue by denissa4** [microsoft/botbuilder-python#1928]
**Is your feature request related to a problem? Please describe.**
Azure Bot released new types of bots, user-assigned managed identity is awesome, but we can't use it because Botbuider-python doesn't have support for it

**Describe the solution you'd like**
Please add user-assigned managed identity for Python SDK 🙏🏻

**Describe alternatives you've considered**
We don't have any alternatives

**Comment by RonMallory** [comment]
related #1790

**Comment by tracyboehrer** [comment]
Duplicate of #1790
