### ISSUE TITLE
'ConsoleAdapter' has no attribute 'run_pipeline' in Console-EchoBot

### ISSUE THREAD

**Issue by omartin2010** [microsoft/botbuilder-python#195]
## Version
4.4.0.b1

## Describe the bug
I'm simply running the Console EchoBot demo and the ConsoleAdapter class is missing the implementation of run_pipeline, and BotAdapter, its base class, doesn't implement it. I'm not familiar with the bot framework, but it seems like the same assembly in c# actually has an implementation for that function/task. 

## To Reproduce
1. Go to the Samples/Console-EchoDot directory
2. type python main.py
3. enter a message at the prompt, hit enter.

## Expected behavior
I guess I would expect an echo.

[bug]

**Comment by axelsrz** [comment]
This error was caused because the samples in master and the published version of the libraries in PyPI were out of sync. This problem should be solved if you update your libraries to 4.4.0b2

**Comment by omartin2010** [comment]
It works, thanks @axelsrz ! looking forward for sample parity with c# :)
