### ISSUE TITLE
HealthCheckResponse missing from botbuilder.schema

### ISSUE THREAD

**Issue by foobarash** [microsoft/botbuilder-python#1968]
## Version
4.14.2

## Describe the bug
HealthCheckResponse missing from botbuilder.schema . Oddly enough this only manifests for me when I install azure.identity in my env. So this is blocking me from using any azure/msgraph related clients that needs a TokenCredential

[ERROR] Runtime.ImportModuleError: Unable to import module 'src.app': cannot import name 'HealthCheckResponse' from 'botbuilder.schema' (/opt/python/botbuilder/schema/__init__.py)

**Comment by tracyboehrer** [comment]
The entire HealthCheck protocol was removed from all SDK repos in 4.14.  There are no plans to bring it back.   It is likely possible the original code could be copied from the releases/4.13 branch.
