### ISSUE TITLE
Method for rendering an Adaptive Card as an Image

### ISSUE THREAD

**Issue by Kevv-J** [microsoft/botbuilder-python#1979]
**Is your feature request related to a problem? Please describe.**
I have a web app running bot framework. I am using Whatsapp Business APIs to connect this app to Whatsapp directly instead of using channels like Twilio.
I want a way to render adaptive cards as images for Whatsapp, similarly to how its done in the Azure Bot for channels like Skype and Slack where interactive adaptive cards are not compatible yet.

**Describe the solution you'd like**
Ideally I'd want to have a method in Bot Framework that will render adaptive cards from JSON to an image.  

**Describe  alternatives you've considered**
Not sure if there are alternatives since the adaptive cards in my app can have dynamic information. For static cards I was planning to render it in [Adaptive Card Designer](https://adaptivecards.io/designer/) and create images from that.

**Additional context**
NA

**Comment by tracyboehrer** [comment]
This is not within the scope of Bot Framework SDK.  We don't render the card in this stack.  At the application (bot) level, something like https://npmjs.com/package/adaptivecards could be used to render to HTML, then some other functionality to render that HTML to an image.

**Comment by Kevv-J** [comment]
Thanks for your response.

for others' reference,
We have used WhatsApp's latest feature "WhatsApp Flows" in WhatsApp to get a similar experience of using Adaptive Cards in MS Teams.
