### ISSUE TITLE
Input.Text placeholder color is not correct when isMultiline is True

### ISSUE THREAD

**Issue by pcanas** [microsoft/botbuilder-python#1989]
## Version
4.14.1

## Describe the bug
Input.Text `placeholder` color is the same as the `value` color when `"isMultiline": True`. If this value is False, `placeholder` shows the appropriate behaviour.

## To Reproduce
1. Create a card with both versions. See the difference.

## Expected behavior
Placeholder should have a lighter color when `"isMultiline": True`

## Screenshots
<img width="444" alt="Captura de pantalla 2023-03-08 a las 16 18 30" src="https://user-images.githubusercontent.com/32467089/223752871-0b882834-6fa8-4a51-8d3a-4fc6a96049ea.png">

**Comment by dmvtech** [comment]
Hi @pcanas 

Thank you for reporting this. A few questions:

- Any idea if this reproduces with any other languages other than Python?
- This appears that you are doing this in Teams. Is that correct? Does it reproduce in other Channels/clients?

**Comment by pcanas** [comment]
Hi @dmvtech thanks for your response! I have no idea whether this reproduces in other languages nor channels/clients. And yes, we are doing this in Teams. I am sorry that I cannot provide more useful information.

**Comment by dmvtech** [comment]
@pcanas  No worries. I'll investigate and check other scenarios. 

Is that input field part of a messaging extension, adaptive card or something else?

**Comment by pcanas** [comment]
@dmvtech It is an adaptive card, version 1.5

**Comment by dmvtech** [comment]
Hi @pcanas 

I can confirm this behavior. It also reproduces language-independent. But, it looks to be an issue with Teams/Teams clients and not the Bot Framework or Adaptive Cards. You could try and file a bug [here](https://github.com/OfficeDev/Microsoft-Teams-Samples), or through other Teams support channels.
