### ISSUE TITLE
Please upgrade version for aiohttp

### ISSUE THREAD

**Issue by lielu** [microsoft/botbuilder-python#1990]
When integrating with langchain in order to build a Teams bot with LLM capabilities, it requires a higher version of aiohttp, and pip is not able to resolve the conflict. 

```
ERROR: Cannot install -r requirements.txt (line 1) and -r requirements.txt (line 3) because these package versions have conflicting dependencies.

The conflict is caused by:
    botbuilder-integration-aiohttp 4.14.3 depends on aiohttp<3.8.0 and >=3.6.2
    langchain 0.0.115 depends on aiohttp<4.0.0 and >=3.8.3
    botbuilder-integration-aiohttp 4.14.3 depends on aiohttp<3.8.0 and >=3.6.2
    langchain 0.0.114 depends on aiohttp<4.0.0 and >=3.8.3
    botbuilder-integration-aiohttp 4.14.3 depends on aiohttp<3.8.0 and >=3.6.2
    langchain 0.0.113 depends on aiohttp<4.0.0 and >=3.8.3
    botbuilder-integration-aiohttp 4.14.3 depends on aiohttp<3.8.0 and >=3.6.2
    langchain 0.0.112 depends on aiohttp<4.0.0 and >=3.8.3
```

Please upgrade the version of aiohttp. Thanks.

**Comment by yuvanist** [comment]
+1 on this! Lower aiohttp version dependency is causing a lot of problems with other packages as well.

**Comment by jpierzchala** [comment]
+1 on this from me as well

**Comment by pablomarin** [comment]
+1 without solving this, it is impossible to use bot framework python sdk and langchain

please fix asap

**Comment by Xrehman** [comment]
+1 on this from me as well we can't able to use langchain capablities due to this version conflict

**Comment by hamin123** [comment]
When we run through the following :- 

To use a local copy of the SDK you can link to these packages with the pip -e option.

pip install -e ./libraries/botbuilder-schema
pip install -e ./libraries/botframework-connector
pip install -e ./libraries/botframework-streaming
pip install -e ./libraries/botbuilder-core
pip install -e ./libraries/botbuilder-ai
pip install -e ./libraries/botbuilder-applicationinsights
pip install -e ./libraries/botbuilder-dialogs
pip install -e ./libraries/botbuilder-azure
pip install -e ./libraries/botbuilder-integration-applicationinsights-aiohttp
pip install -e ./libraries/botbuilder-adapters-slack
pip install -e ./libraries/botbuilder-integration-aiohttp
pip install -e ./libraries/botbuilder-testing

We get errors like these in many cases : 

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
langchain 0.0.172 requires aiohttp<4.0.0,>=3.8.3, but you have aiohttp 3.7.4.post0 which is incompatible.
langchain 0.0.172 requires async-timeout<5.0.0,>=4.0.0; python_version < "3.11", but you have async-timeout 3.0.1 which is incompatible.

others are 

>> pip install -r ./libraries/botframework-connector/tests/requirements.txt

Reported Issues

langchain 0.0.172 requires aiohttp<4.0.0,>=3.8.3, but you have aiohttp 3.7.4.post0 which is incompatible.
langchain 0.0.172 requires async-timeout<5.0.0,>=4.0.0; python_version < "3.11", but you have async-timeout 3.0.1 which is incompatible.
langchain 0.0.172 requires PyYAML>=5.4.1, but you have pyyaml 5.4 which is incompatible.


>> pip install -e ./libraries/botbuilder-core

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
botbuilder-integration-aiohttp 4.15.0 requires yarl<=1.4.2, but you have yarl 1.7.2 which is incompatible.


>> pip install -e ./libraries/botbuilder-schema

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
botbuilder-integration-aiohttp 4.15.0 requires yarl<=1.4.2, but you have yarl 1.7.2 which is incompatible.


>> pip install -e ./libraries/botframework-connector

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
botbuilder-integration-aiohttp 4.15.0 requires yarl<=1.4.2, but you have yarl 1.7.2 which is incompatible.

It seems, we can not move to using latest version of botbuilder packages without resolving these issues.
