### ISSUE TITLE
`botbuilder-integration-aiohttp` incompatible with Python 3.11 due to limit on `yarl` version

### ISSUE THREAD

**Issue by me4502** [microsoft/botbuilder-python#2015]
## Version
```
botbuilder-integration-aiohttp==4.14.4
```

## Describe the bug
Due to the pinned version of `yarl` added in https://github.com/microsoft/botbuilder-python/pull/1507, this package cannot be used under Python 3.11. `yarl` gained Python 3.11 support via this PR, https://github.com/aio-libs/yarl/issues/706 which was released in 1.8.1(?), however the pinned range of yarl prevents versions higher than 1.4.2 from being installed.

## To Reproduce
1. Install `botbuilder-integration-aiohttp==4.14.4` under Python 3.11
2. Note the failure when installing the `yarl` wheel, which is described in https://github.com/aio-libs/yarl/issues/706

## Expected behavior
This library can be installed under Python 3.11, or at least doesn't pin packages in a way that prevents working around the compatibility issues.

While the pin here appears to have been so that Python 3.7 will work without having to pin an extra dependency, given this completely breaks 3.11 I feel it would make sense to not have any pinning, and allow Python 3.7 users to pin `yarl` themselves to resolve any version issues. That way both 3.7 and 3.11 are possible to use with this library, unlike the current setup where 3.11 is impossible to use.

**Comment by madinabatlumi** [comment]
+1 on this

**Comment by mohdhammad786** [comment]
> Thanks @me4502, @madinabatlumi. We are looking into this.

hi guys can you also do something for this issue https://github.com/microsoft/botbuilder-python/issues/2019

**Comment by kostyaplis** [comment]
It seems that python 3.11 compatibility was fixed in 4.14.5

**Comment by aacebo** [comment]
I am working on a few different PRs to update outdated dependencies that prevent devs from importing. This is the first PR https://github.com/microsoft/botbuilder-python/pull/2060

**Comment by aacebo** [comment]
closing because this is no longer an issue
