### ISSUE TITLE
botbuidler support for  regex== 2022 and above

### ISSUE THREAD

**Issue by mohdhammad786** [microsoft/botbuilder-python#2019]
Description:

I'm currently working on building a chatbot using Azure Bot Builder SDK in conjunction with OpenAI. In my project, I'm relying on the OpenAIEmbedding class from the langchain package, which utilizes Tiktoken. However, I've run into an issue due to dependency conflicts with Tiktoken. Specifically, Tiktoken requires regex version 2022 or higher, while the Bot Builder package supports only up to regex version 2019.

Feature Request:

I kindly request adding support for Tiktoken's regex version 2022 or higher in the OpenAIEmbedding class within the langchain package. This update would resolve the dependency conflicts and enable smoother integration of OpenAI into projects using Azure Bot Builder SDK.

Additional Information:

Current Behavior: Currently, the OpenAIEmbedding class in langchain relies on Tiktoken, which necessitates a regex version that is not compatible with the Bot Builder SDK's regex version support.

Desired Behavior: The botbuilder  classes should be updated to support Tiktoken's dependency on regex version 2022 or higher t

Impact of the Feature:

This feature would benefit developers working on chatbot projects that use Azure Bot Builder SDK and OpenAI. It would eliminate dependency conflicts, allowing for a seamless integration experience.

**Comment by mohdhammad786** [comment]
Thanx for assigning this ramfattah, this feature has a great impact on Microsoft ecosystem since azure open ai and botbuilder can easily work together

**Comment by ramfattah** [comment]
Thanks @mohdhammad786, I'll discuss this internally with the Bot Framework SDK engineers. 

We will report back soon. 
Thanks.

**Comment by ramfattah** [comment]
Hello @mohdhammad786,

Thank you for your request. Our Bot Framework Python SDK will soon end support in November 2023. Because of this, we are focusing on security fixes. We will add your request to our backlog, but we don't have an ETA at the moment.

Thank you.

**Comment by ramfattah** [comment]
CC @tracyboehrer

**Comment by tracyboehrer** [comment]
@mohdhammad786 Can you check out https://github.com/microsoft/botbuilder-python/pull/2050 and see if this works for you?
