### ISSUE TITLE
botbuilder incompatible with tiktoken package

### ISSUE THREAD

**Issue by mohdhammad786** [microsoft/botbuilder-python#2020]
I'm currently working on building a chatbot using Azure Bot Builder SDK in conjunction with OpenAI. In my project, I'm relying on the OpenAIEmbedding class from the langchain package, which utilizes Tiktoken. However, I've run into an issue due to dependency conflicts with Tiktoken. Specifically, Tiktoken requires regex version 2022 or higher, while the Bot Builder package supports only up to regex version 2019.

**Comment by ramfattah** [comment]
Duplicate https://github.com/microsoft/botbuilder-python/issues/2019
