### ISSUE TITLE
Extensibility for Teams AI - ability to add to User Agent for Teams AI telemetry

### ISSUE THREAD

**Issue by corinagum** [microsoft/botbuilder-python#2033]
Related to https://github.com/microsoft/botbuilder-js/issues/4552, https://github.com/microsoft/botbuilder-dotnet/issues/6701

Request is from https://github.com/microsoft/teams-ai team

[ConnectorFactoryImpl](https://github.com/microsoft/botbuilder-dotnet/blob/617394d6ff834b0804cceabff2ed9d6e06342cd4/libraries/Microsoft.Bot.Connector/Authentication/ConnectorFactoryImpl.cs#L41)

We are hoping to have the ability to add Teams AI information for SMBA to parse for telemetry.

Since Teams AI is JavaScript first, we request this would be done in the JS SDK first with fast follow for C# and Python

**Comment by aacebo** [comment]
closing since we ended up using a pre-existing parameter to the `CloudAdapter`
