### ISSUE TITLE
Support Single Tenant AppType

### ISSUE THREAD

**Issue by tracyboehrer** [microsoft/botbuilder-python#2043]
1) ConfigurationServiceClientCredentialFactory
    - Config.APP_TYPE ("MultiTenant", "SingleTenant", "UserAssignedMsi")
    - Handle Multi or Single tenant
    - Default to MultiTenant if blank
    - Error for UserAssignedMsi (not currently supported in Python MSAL package)
2) PasswordServiceClientCredentialFactory
    - Match DotNet
3) AppCredentials (and subclasses)
    - Resolve differences from DotNet

**Comment by jnissin** [comment]
Just pitching in here that this feature would be highly appreciated. If anyone has any known workarounds for this I'm all ears.

**Comment by tracyboehrer** [comment]
If someone feel adventurous, there is a test version on PyPi for this.  Version 0.0.1.

Can use this doc.  It hasn't been updated to indicate Pyton support but it works.  I did have to update AZ to 2.55.0.

https://learn.microsoft.com/en-us/azure/bot-service/provision-and-publish-a-bot

Attached is the EchoBot sample.  It does have modified ARM templates to support SingleTenant.  The only other change in the bot is the config.py.

[02.echo-bot.zip](https://github.com/microsoft/botbuilder-python/files/13640843/02.echo-bot.zip)

**Comment by faniereynders** [comment]
This is great @tracyboehrer - thank you! However, it seems like there are conflicts when using it with `botbuilder-dialogs@4.14.6` as it depends on `botbuilder-schemas@4.14.6` and `botbuilder-integration-aiohttp@0.0.1` depends on `botbuilder-schemas@0.0.1`

**Comment by faniereynders** [comment]
> This is great @tracyboehrer - thank you! However, it seems like there are conflicts when using it with `botbuilder-dialogs@4.14.6` as it depends on `botbuilder-schemas@4.14.6` and `botbuilder-integration-aiohttp@0.0.1` depends on `botbuilder-schemas@0.0.1`

When referencing `0.0.1` for all the bot builder packages it seems to work, but the SSO only seems to work in web channel, in Teams, it is not.
