### ISSUE TITLE
New version breaks BotAdapter interface

### ISSUE THREAD

**Issue by dciborow** [microsoft/botbuilder-python#205]
## Version
4.4.0.b2

## Describe the bug
A class created that inherits BotAdapter now throws this error. 
AttributeError: 'StringAdapter' object has no attribute 'run_middleware'

## To Reproduce
EchoBot example

## Expected behavior
The interface previously had this function. Not sure if it was meant to be removed. 

## Screenshots
![image](https://user-images.githubusercontent.com/9027725/59243597-bf4ce900-8bde-11e9-8a14-15e760442c5e.png)

## Additional context
dciborow@microsoft.com

[bug]

**Comment by axelsrz** [comment]
@dciborow yes, this change was intentional. The name of the interface is now aligned with [C#](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/BotAdapter.cs), and the new name is run_pipeline. 

The functionality stay the same.
