### ISSUE TITLE
Recommended change to 3.8.6 or above

### ISSUE THREAD

**Issue by jamiesun** [microsoft/botbuilder-python#2059]
https://github.com/microsoft/botbuilder-python/blob/7b064bb9f916afc10e931f3713183f57e1d7ca47/libraries/botbuilder-integration-aiohttp/setup.py#L13

I have a conflict when introducing llamaindex, which requires version 3.8.6 or higher!

**Comment by basilisk487** [comment]
It also gets us flagged for 5 aiohttp vulnerabilities (1 high severity, 4 medium)

**Comment by tracyboehrer** [comment]
ACK on this.  3.9.2 is causing some issue we'll need to resolve.
