### ISSUE TITLE
botbuilder-integration-aiohttp - Python 3.12 compatibility

### ISSUE THREAD

**Issue by ykursav** [microsoft/botbuilder-python#2082]
Hello,

It would be great if someone would deploy new pip package to pypi for botbuilder-integration-aiohttp package, because I saw aiohttp version updated but no deployment to pypi yet. Currently, I am unable to use with 3.12

**Comment by iMicknl** [comment]
@tracyboehrer are there any plans to support Python 3.12?

**Comment by tracyboehrer** [comment]
Generally speaking, we aim to support newer versions of languages.  Though it sometimes takes a bit.  Is the blocker just the botbuilder-integration-aiohttp package using and older version of aiohttp?

**Comment by ClaireRich** [comment]
Hey, my team is also waiting on this and it is currently blocking us from updating to 3.12

**Comment by tracyboehrer** [comment]
4.15.0 was released which updates aiohttp.  Can you let us know if this resolved?
