### ISSUE TITLE
Python SDK GA Timeline

### ISSUE THREAD

**Issue by Adityagrao** [microsoft/botbuilder-python#210]
Will Microsoft Push the Python Development as to GA for 4.5? ie features showcased in Build 2019, such as Adaptive Dialogs

**Comment by brownsec** [comment]
I am very interested in knowing the answer to this well. This will help me prioritize my chatbot project.

**Comment by cleemullins** [comment]
The Python SDK is currently Targeting GA in the November/December time frame. This is planned to include parity with the existing (non-adaptive) SDKs. 

We will be releasing additional previews of the Python SDK in sync with our regular SDK cadence. Each preview brings parity closer, including test coverage, samples, docs, and functionality.
