### ISSUE TITLE
Need to upgrade aiohttp dependency to 3.9.4

### ISSUE THREAD

**Issue by frankqianms** [microsoft/botbuilder-python#2106]
### Use this [query](https://github.com/Microsoft/botbuilder-python/issues?q=is%3Aissue+is%3Aopen++label%3Afeature-request+) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
To fix the vulnerability, we need to upgrade aiohttp to 3.9.4. However, botbuilder-integration-aiohttp 4.14.8 depends on aiohttp==3.8.5.

**Describe the solution you'd like**
Upgrade aiohttp to 3.9.4.

**Comment by tracyboehrer** [comment]
This happened via dependabot and have been merged with main.  Will be in the next release.
