### ISSUE TITLE
use managed identity in Python bot

### ISSUE THREAD

**Issue by frankqianms** [microsoft/botbuilder-python#2107]
### Use this [query](https://github.com/Microsoft/botbuilder-python/issues?q=is%3Aissue+is%3Aopen++label%3Afeature-request+) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
According to [this doc](https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=userassigned%2Caadv2%2Ccsharp#:~:text=The%20Java%20version%20of%20the%20Bot%20Framework%20SDK%20only%20supports%20multi%2Dtenant%20bots.%20The%20Python%20version%20of%20the%20Bot%20Framework%20SDK%20supports%20multi%2Dtenant%20and%20single%2Dtenant%20bots.%20The%20C%23%20and%20JavaScript%20versions%20support%20all%20three%20application%20types%20for%20managing%20the%20bot%27s%20identity.), the Python version of the Bot Framework SDK supports multi-tenant and single-tenant bots. Since Teams-ai depends on Bot Framework SDK, Python bots here do not support managed identity either. 

**Describe the solution you'd like**
Please let Python bots support managed identity.

**Comment by tracyboehrer** [comment]
This is not possible until the MSAL package for Python supports it.

**Comment by frankqianms** [comment]
Got it! Thank you.

**Comment by jannikmi** [comment]
Why has this been closed? I think it is a valid and important feature that bots (and all other cloud ressource types) support managed identities. This issue is still relevant even if it cannot be resolved at the moment.

I believe this is a related PR in the MSAL: https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/480
