### ISSUE TITLE
NumberPrompt constructor references ConfirmPrompt when trying to inherit from Prompt class

### ISSUE THREAD

**Issue by awaemmanuel** [microsoft/botbuilder-python#216]
## Version
v4.4.0.b2

## Describe the bug
NumberPrompt dialog prompt has a bug that references `ConfirmPrompt` , which is not defined in the class. when it calls on it's `super` when inheriting from `Prompt`

Current code in master:
```
class NumberPrompt(Prompt):
    # TODO: PromptValidator
    def __init__(self, dialog_id: str, validator: object, default_locale: str):
        super(ConfirmPrompt, self).__init__(dialog_id, validator)
        self._default_locale = default_locale
```

Should be  

```
class NumberPrompt(Prompt):
    # TODO: PromptValidator
    def __init__(self, dialog_id: str, validator: object, default_locale: str):
        super(NumberPrompt, self).__init__(dialog_id, validator)
        self._default_locale = default_locale  
```

## To Reproduce
Code in master branch can be found [here](https://github.com/microsoft/botbuilder-python/blob/master/libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/number_prompt.py#L13-L17)

## Expected behavior
The `super` method should be called with the class name, `NumberPrompt`, in which it is used and inherit from a class that it can derive from. 

## Additional context

[bug]

**Comment by Zerryth** [comment]
Looks like this is resolved already in master as of today:

https://github.com/microsoft/botbuilder-python/blob/master/libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/number_prompt.py#L16

Resolving
