### ISSUE TITLE
Bot Builder Python SDK issues with incompatible Python names

### ISSUE THREAD

**Issue by jjstirrup** [microsoft/botbuilder-python#2161]
## Version
What package version of the SDK are you using.

## Describe the bug
Give a clear and concise description of what the bug is.

## To Reproduce
1. Follow instructions to here: https://github.com//microsoft/botbuilder-python?tab=readme-ov-file#running-unit-tests
2. Run 'pytest'
3. See error
____ ERROR collecting libraries/botbuilder-integration-applicationinsights-aiohttp/tests/test_aiohttp_processor.py ____
ImportError while importing test module 'C:\Users\XXXXXXX\botbuilder-python\libraries\botbuilder-integration-applicationinsights-aiohttp\tests\test_aiohttp_processor.py'.
Hint: make sure your test modules/packages have valid Python names.

## Expected behavior
Give a clear and concise description of what you expected to happen.

**Comment by gandiddi** [comment]
Hi @jjstirrup, please run the [_pip install -e commands_](https://github.com//microsoft/botbuilder-python?tab=readme-ov-file#using-the-sdk-locally) before running the unit tests. If you still face the same issue, let me know which Python and SDK versions you are using.

**Comment by gandiddi** [comment]
@jjstirrup Hope you were able to resolve the issue. Please let me know if you're still experiencing any problems or need further assistance. Thanks!

**Comment by gandiddi** [comment]
Closing the issue as we haven't heard back from the user. Feel free to reopen or create a new issue if further assistance is needed. Thanks!
