### ISSUE TITLE
Update azure-cosmos to latest version to support DefaultAzureCredential

### ISSUE THREAD

**Issue by MS-LJL** [microsoft/botbuilder-python#2162]
### Description

**Is your feature request related to a problem? Please describe.**
Current python bot framework has a dependency on azure-cosmos 3.2.0, but this version doesn't support use of DefaultAzureCredential to access Azure cosmos db. 

**Describe the solution you'd like**
Update the usage of azure-cosmos to the recent version to support DefaultAzureCredential

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by tracyboehrer** [comment]
@MS-LJL I'm going to close this one in favor of: https://github.com/microsoft/botbuilder-python/issues/2047
