### ISSUE TITLE
[botbuilder.testing] Relax dependency to allow pytest 8

### ISSUE THREAD

**Issue by alexrecuenco** [microsoft/botbuilder-python#2168]
I see the requirements was written in #1637, a few years back

Can the pytest requirements be relaxed to allow pytest 8? Or is there anything specific that breaks with pytest 8. I was looking at the implementation of the module, and the changelog in pytest and I can't see anything that should be a big conflict

https://github.com/microsoft/botbuilder-python/blob/0fba27be15cd72bffb7f34bf1ed20c05c3df0957/libraries/botbuilder-testing/setup.py#L12

**Comment by tracyboehrer** [comment]
@alexrecuenco Well that's just it.  We don't know if 8 breaks something without testing it.  At the very least, restricting to major versions is more reasonable.  At least for dependencies that adhere to semver.  Not all do though, and any version can be breaking.

More than happy to look into this though.  There is also no reason not to update older dependencies.

**Comment by alexrecuenco** [comment]
Let me know if I can be of help testing anything in particular.
