### ISSUE TITLE
[URGENT] Sign in Button inside the OAuth Card created by OAuthPrompt Dialog is not being rendered on MS Teams anymore.

### ISSUE THREAD

**Issue by Kevv-J** [microsoft/botbuilder-python#2169]
## Version
4.14.3

## Describe the bug
I have setup OAuth with Azure Bot as outlined in [Microsoft Documentation](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/add-authentication). It was working fine before. I was able to sign in and chat with bot. 
![image](https://github.com/user-attachments/assets/dcc296a1-5ab4-408d-8670-c4f37903b814)
But now the Sign in Button is not visible
![image](https://github.com/user-attachments/assets/9c6ec78f-a3f7-4e45-82d9-cbbf5eed4320)

## To Reproduce
1. Setup OAuth with MS Teams as outlined [here](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-teams-authentication/python)
2. Try Signing in with OAuth
3. Unable to Sign in because the button is not being rendered on MS Teams

## Expected behavior
I should be able to sign in to ms teams using OAuth as it used to work earlier. as shown in the sample.

**Comment by Kevv-J** [comment]
This works fine from webchat btw
![image](https://github.com/user-attachments/assets/a92c5dd2-9e92-4fbc-970b-49390c32207f)

**Comment by Kevv-J** [comment]
I just checked with a Client, they faced this in production today as well. Only new users are facing this issue because older users are logged in already.

Please look into this urgently.

**Comment by tracyboehrer** [comment]
When did this start?  BTW, this doesn't appear to be language or SDK version specific.

**Comment by tracyboehrer** [comment]
This is a Teams issue.  I believe a fix is in progress.

**Comment by Kevv-J** [comment]
Hi @tracyboehrer,

Thanks a lot for forwarding this issue to the correct Team.

I had raised a support ticket with Microsoft as well and got a reply saying they've applied to fix. I've tested it and its working for me although I've not got confirmation from the client whether its fixed in their prod environment.

Thanks a lot again.

**Comment by Kevv-J** [comment]
Client has confirmed issue is fixed in prod as well.
