### ISSUE TITLE
MS Teams Bot - messages take 12s from user to the bot

### ISSUE THREAD

**Issue by gykung** [microsoft/botbuilder-python#2181]
I have a Teams bot, written in Python, bot framework, run on a on-premise VM, connected via ngrok to my bot app for my enterprise. 

User messages from MS Teams to the python on VM: takes 5-12 seconds

Reply from the Python bot to user: instant, no discernible lag.

Does anyone else face a similar issue? What’s the typical latency expected?

Sorry for asking this question here, I am not sure where else to ask this.

Expected behavior

Nearly zero lag.

Actual behavior

5-12 seconds lag.

**Comment by dmvtech** [comment]
@gykung All signs point to this being an issue on the Teams side of things. Please pursue assistance through Teams. If you find more information that says otherwise, please let us know and we will investigate.
