### ISSUE TITLE
Missing appType Parameter in ARM Template for Python Bot Deployment

### ISSUE THREAD

**Issue by diasirish** [microsoft/botbuilder-python#2187]
Environment:

	•	Language: Python
	•	Template: parameters-for-template-BotApp-with-rg.json
	•	Documentation: [Provisioning Bot with ARM template](https://learn.microsoft.com/en-us/azure/bot-service/provision-app-service?view=azure-bot-service-4.0&tabs=multitenant%2Cexistingplan)

Issue Description:
I am attempting to deploy a multi-tenant bot using the ARM template provided in the official Microsoft repository. The instructions require setting the appType parameter for both App Service and Azure Bot resources to ensure consistent identity management configurations. According to the documentation, this parameter is required and should be set to one of the following values: “MultiTenant”, “SingleTenant”, or “UserAssignedMSI”.

Problem:
The ARM template parameters-for-template-BotApp-with-rg.json intended for Python does not include the appType parameter. This omission could lead to inconsistencies in deployment configurations and potential deployment failures due to missing required parameters.

Steps to Reproduce:

	1.	Download the ARM template from the official Microsoft Bot Framework SDK repository.
	2.	Open the parameters-for-template-BotApp-with-rg.json file.
	3.	Notice the absence of the appType parameter in the list of parameters.

Expected Behavior:
The ARM template should include the appType parameter to allow developers to specify the identity management configuration, consistent with the deployment documentation.

Actual Behavior:
The appType parameter is missing from the ARM template, leading to potential confusion and misconfiguration during deployment.

Impact:
Potential deployment failure or incorrect configuration for developers deploying Python-based bots using the ARM template.

Suggested Fix:
Update the ARM template to include the appType parameter or adjust the documentation to accurately reflect the parameters needed for Python-based bot deployments.

Additional Information:
N/A

Screenshots/Logs:
(If applicable, add screenshots or logs to help explain the issue.)

This format provides a clear, structured way to report the issue, ensuring that all necessary information is communicated effectively. Adjust the specifics according to your situation.

**Comment by dmvtech** [comment]
Hi @diasirish 

Thank you for informing us of this. Can you please clarify on the location you are referring to here:

> 1.	Download the ARM template from the official Microsoft Bot Framework SDK repository.
