### ISSUE TITLE
Work in GovCloud(s)

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botbuilder-python#232]
## Issue
Users need to perform manual changes to get template and samples code working in Azure US Gov (a National Cloud). These changes are minimal but obtrusive as we don't describe when a user would normally perform these changes (which is reliant on whether the user is using Public Azure or a [National Cloud](https://docs.microsoft.com/en-us/graph/deployments)).

This also adds friction in that the samples in [botbuilder-samples](https://github.com/microsoft/botbuilder-samples) aren't as easily deployable as deploying to Public Azure (no code changes required).

## Proposed change
Clean up BotFrameworkAdapter by having it check/default for BotOpenIdMetadata and ChannelService environment variables in the constructor/initializer in JS and Python.

These variables are configured in our deployment settings on Azure.

## Component Impact 
- [ ] **BotFrameworkAdapter** (JS, Python)
- [ ] **AuthenticationConstants** (JS, Python)
  - These are namespaced as Constants in `botframework-connector` and not exposed to the developer. In C# these constants are public.

## Tracking Status
**Dotnet SDK**
PR: .[netcore](https://github.com/microsoft/botbuilder-dotnet/pull/1926), needs update/fix

**Javascript SDK**
PR: microsoft/botbuilder-js#975

**Comment by stevengum** [comment]
Cross linking [TODO-type comment](https://github.com/microsoft/botbuilder-python/pull/262/files#diff-19da6a20384c34f20bda25f97a7643aeR53) in PR #262.
