### ISSUE TITLE
[Teams] Provide a Teams connector that models the standard connector

### ISSUE THREAD

**Issue by sgellock** [microsoft/botbuilder-python#258]
**Is your feature request related to a problem? Please describe.**
Teams connector should be discoverable and "reasonably unified" with the SDK's regular connector.

**Additional context**
This rolls up to 
https://github.com/microsoft/botframework-sdk/issues/5462

[enhancement]

**Comment by EricDahlvang** [comment]
Closing, since this is now represented here: https://github.com/microsoft/botbuilder-python/blob/master/libraries/botframework-connector/botframework/connector/teams/teams_connector_client.py
