### ISSUE TITLE
Is this production ready yet

### ISSUE THREAD

**Issue by wassimseif** [microsoft/botbuilder-python#261]
I'm really sorry for asking the question here, but I couldn't find any other place.
Since v4.5.0 is "Officially launched" does that mean that I can use this library for production bots? 
I know the documentation says that it's Preview but I figured that maybe it's not updated 

[question]

**Comment by Zerryth** [comment]
Hi @wassimseif! 

The Python SDK is in "Preview 2" stage. The team thought it would be best to keep the version numbers across the various language SDKs in sync, which is why you see issues labelled `4.5` -- and some now even `4.6` for the Bot Framework release cycle.
