### ISSUE TITLE
ActivityHandler should be an abstract base class

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-python#265]
## Version
4.5.0b2

## Describe the bug
ActivityHandler should be an abstract base class (`ABC`). This may get rid of the following pylint error: `disable=unused-argument`

[bug]

**Comment by johnataylor** [comment]
I don't think I agree. It is not an abstract base class in the C# and simply forcing it to be by (for example) making the OnMessage method abstract doesn't seem like the right thing to do.

So I think you are going to have to address your linting problems in another way (can you mark an exception in the code for example?)
