### ISSUE TITLE
Remove Mention Support

### ISSUE THREAD

**Issue by tracyboehrer** [microsoft/botbuilder-python#273]
**Describe the solution you'd like**
Add Remove Mention support as JS and C#.  See ActivityExtensions for a reference of Mention related methods.  To remove mentions from Activity.Text, see ActivityExtensions.RemoveMentionText and ActivityExtensions.RemoveRecipientMention.  Note that in JS it is TurnContext.removeMentionText.

**Describe alternatives you've considered**
None

**Additional context**
I have implemented SkypeMentionNormalizeMiddleware on all platforms to correct Skype mentions.  The user could still make use of this middleware, but would have to manually remove the mention from Activity.Text to have the same functionality as the other platforms.

[enhancement]

**Comment by sgellock** [comment]
looks like this was addressed in #291
