### ISSUE TITLE
Revisiting configuration for botbuilder-python SDK bots

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-python#277]
### Ask:
The method of loading configuration for a Python bot (e.g. `MicrosoftAppId`, `MicrosoftAppPassword`, `LuisAppId`) needs to meet the following criteria:
- Visually simple
   - There shouldn't be a 100 line python file just to load configuration for a bot.
- Exportable from Web App Bot resources on Azure
   - When users download a bot's code from a Web App Bot a dialog pops up to prompt the user to include their Web App's Application Settings. The Application Settings includes the `MicrosoftAppId`, etc. and is placed into a language/runtime specific file.
   - i.e. `.env` for JavaScript/Node.js and `appsettings.json` for C#/dotnetcore
   - Without any changes to the downloaded bot's code, the locally running bot will use the same configuration as it uses while deployed on Azure

The current status of the [`config.py`](https://github.com/microsoft/botbuilder-python/blob/76a228d39e04c2803d9deb2481cd4108d1d2d4d3/samples/python_flask/13.core-bot/config.py) ([`76a228d`](https://github.com/microsoft/botbuilder-python/tree/76a228d39e04c2803d9deb2481cd4108d1d2d4d3)) in the flask core-bot does not meet the second point above, as it would need additional code to point to a specific local file:

```python
#!/usr/bin/env python3
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

import os

""" Bot Configuration """


class DefaultConfig(object):
    """ Bot Configuration """

    PORT = 3978
    APP_ID = os.environ.get("MicrosoftAppId", "")
    APP_PASSWORD = os.environ.get("MicrosoftAppPassword", "")
    LUIS_APP_ID = os.environ.get("LuisAppId", "")
    LUIS_API_KEY = os.environ.get("LuisAPIKey", "")
    # LUIS endpoint host name, ie "https://westus.api.cognitive.microsoft.com"
    LUIS_API_HOST_NAME = os.environ.get("LuisAPIHostName", "")
```

**Comment by axelsrz** [comment]
Per chat with @daveta and @stevengum we concluded that no further changes will be needed in the config mechanism. I'm closing this issue.
