### ISSUE TITLE
UnsupportedMediaType - Azure Linux WebApp

### ISSUE THREAD

**Issue by masyanru** [microsoft/botbuilder-python#312]
## Version
4.5.0b4

## Describe the bug
I've built docker container for this example https://github.com/microsoft/botbuilder-python/tree/master/samples/06.using-cards
Localy with Bot Framework Emulator everything works fine, but when I am trying to run this container inside Linux Web App in Azure I get "There was an error sending this message to your bot: HTTP status code UnsupportedMediaType" in every channel (WebChat, Telegram, Teams etc.)

btw, if I connect from Bot Framework Emulator to container in Linux Web App - it works.

Dockerfile
```
FROM python:3
COPY ./app /app
WORKDIR /app
RUN pip install -r requirements.txt
EXPOSE 3978
CMD [ "python", "-u", "main.py" ]`
```

[bug]

**Comment by carlosscastro** [comment]
@axelsrz  @daveta Any updates here?

**Comment by axelsrz** [comment]
We should take that change in the samples, @mdrichardson if you want to submit the PRs go ahead, if not I can do it.

**Comment by mdrichardson** [comment]
@axelsrz Would the PR only need that line changed in each sample? I'm comfortable doing that...just haven't work in Python enough to do much else. But if that's all that's needed, let me know and I'll work up a PR.
