### ISSUE TITLE
Port new CosmosDB Partitioned Storage from C#

### ISSUE THREAD

**Issue by garypretty** [microsoft/botbuilder-python#327]
A new Cosmos DB storage implementation which utilizes the v3 API and handles the partition key internally has been implemented in C#.

C# implementation is here https://github.com/microsoft/botbuilder-dotnet/pull/2613

**Comment by mdrichardson** [comment]
Just FYI to anybody that might want to jump on this. I'm writing the tests for this right now. It's going to take a bit as I'll also write a Storage Base Tests class, similar to [this PR](https://github.com/microsoft/botbuilder-js/pull/1371)
