### ISSUE TITLE
cookiecutter and Empty Bot project is not a valid zip archive

### ISSUE THREAD

**Issue by masyanru** [microsoft/botbuilder-python#367]
Hi,

from this doc - https://github.com/microsoft/botbuilder-python/tree/master/generators

creating an Echo Bot project works fine

![Screenshot 2019-10-28 at 18 05 08](https://user-images.githubusercontent.com/19715692/67690205-88b91480-f9ad-11e9-97b6-247173c25ec8.png)

but an Empty Bot project:
```
cookiecutter https://github.com/microsoft/botbuilder-python/releases/download/Templates/empty.zip
Zip repository https://github.com/microsoft/botbuilder-python/releases/download/Templates/empty.zip is not a valid zip archive:
```

![Screenshot 2019-10-28 at 18 05 14](https://user-images.githubusercontent.com/19715692/67690223-8fe02280-f9ad-11e9-9bc5-82a9c6be9c45.png)

and that's all.

[bug]

**Comment by v-kydela** [comment]
Hello @masyanru 

The Empty Bot template has not been published yet. You can see [here](https://github.com/microsoft/botbuilder-python/releases/tag/Templates) that the only published template is echo.zip. Expect empty.zip to be published later today.
