### ISSUE TITLE
Sample code snippets

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/botbuilder-python#4]
add state
Simple Conversation Modeling (Echo Bot, primitives)
Complex Conversation Modeling (Alarm Bot, multi-dialogs, cards)
LUIS
QnA
Cards
Proactive Messages
Middleware
Directline
Support

**Comment by johnataylor** [comment]
We will add samples similar to those in JavaScript and .NET as the higher level abstractions are added.

**Comment by vijaysaimutyala** [comment]
@vishwacsena I've tested and implemented the sample from Wiki and it works fine. I wanted to implement the same using a Flask and Waitress server instead of a simple HTTPServer. Any pointers that can help me start ?

**Comment by stevengum97** [comment]
@vijaysaimutyala, I haven't used Waitress before, but prior to the current minimalistic setup, we had a flask sample, which can be found under this commit [_here_](https://github.com/Microsoft/botbuilder-python/blob/702460a1606750650d8f7a20bdf7b11b763a5e1e/samples/Echo.Connector.Bot/main.py).

**Comment by vijaysaimutyala** [comment]
Waitress is a production webserver below which a flask app runs. Thanks for the link. I'm looking for the same. It would be nice to leave a link to the flask sample in the wiki.

I have one more question though. Can we expect this SDK to include the UI elements like cards, buttons and carousel ?

**Comment by vijaysaimutyala** [comment]
@stevengum97 I referred to the FAQ and yes, we'll be allowed to user the UI elements. Thanks.
