### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by tracyboehrer** [microsoft/botbuilder-python#418]
https://github.com/microsoft/botframework-sdk/projects/14

**Comment by tracyboehrer** [comment]
We will need to modify samples with ARM templates and update Docs (or provide README instructions).

@Kaiqb Kamran, Steven pushed an arm template and steps that match almost exactly (skip 5.1 in the linked steps) as described in https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp

**Comment by stevengum** [comment]
Cross linking #415

**Comment by beyhangl** [comment]
could you update deployment procedure for python ? 

https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp

**Comment by tracyboehrer** [comment]
@beyhangl Thanks!  We're still in the process finalizing our deployment procedure.  We'll also be updating all of the relevant docs.  We expect this to happen in the Dec 10 release.

**Comment by tracyboehrer** [comment]
ARM templates for deploying to a new or existing resource group per [Deploy your bot](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp) in [Sample branch](https://github.com/microsoft/BotBuilder-Samples/tree/trboehrer-move-samples)
