### ISSUE TITLE
Inspection middleware needs to be updated to better handle Teams

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/botbuilder-python#428]
Inspection middleware needs to be updated to check for TeamID and use that, otherwise use conversationID

**Comment by johnataylor** [comment]
Doing this brings the Python into alignment with the JavaScript and C#

**Comment by tracyboehrer** [comment]
@Virtual-Josh Josh, what is the status on this?  Do you have more info we could use to close the issue out?

**Comment by tracyboehrer** [comment]
Closing.  Not actionable.
