### ISSUE TITLE
Naming inconsistencies in teams_activity_handler

### ISSUE THREAD

**Issue by johnataylor** [microsoft/botbuilder-python#449]
Naming inconsistencies.

1) none of these function names should have _activity at the end 

on_teams_signin_verify_state_activity
on_teams_file_consent_activity
on_teams_o365_connector_card_action_activity
on_teams_app_based_link_query_activity
on_teams_messaging_extension_query_activity
on_teams_messaging_extension_select_item_activity
on_teams_messaging_ etension_submit_action_dispatch_activity
on_teams_messaging_extension_fetch_task_activity
on_teams_messaging_extension_configuration_query_settings_url_activity                                     on_Teams_messaging_extension_configuration_setting_activity on_teams_messaging_extension_card_button_clicked_activity
on_Teams_task_module_fetch_activity
on_teams_task_module_submit_activity

1) Typo, the word "extension"  is spelt "etension" in on_teams_messaging_ etension_submit_action_dispatch_activity

**Comment by johnataylor** [comment]
@Virtual-Josh @Traceytu great to see this taking shape 😄 I realize this is on a branch but creating an issue anyhow - note the typo on the function name too

(Incidentally next time just go ahead and PR straight into master - we don't uses staging branches on the SDK repos - we only do that in the samples repo.)

**Comment by Virtual-Josh** [comment]
https://github.com/microsoft/botbuilder-python/pull/466/files

Done
