### ISSUE TITLE
Update 05.multi-turn-prompt with C# / JS changes

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/botbuilder-python#471]
## Version
What package version of the SDK are you using. n/a (master branch)

## Describe the bug
An attachment step, attachment prompt, and attachment prompt validator were added to the C# and JavaScript 05.Multi-turn-prompt sample. These changes are not yet reflected in the corresponding Python sample.

## To Reproduce
1. Compare Python dialog to the C# and JS versions of the dialog, specifically the constructor and the _picture step_ method.
   - Python: [constructor](https://github.com/microsoft/botbuilder-python/blob/ec70a70a057ef1458418e253198c219a8107e39f/samples/05.multi-turn-prompt/dialogs/user_profile_dialog.py#L30-L48)
   - C#: [in constructor](https://github.com/microsoft/BotBuilder-Samples/blob/c1e2eabeccac2c544e0c1dbac3f0fe92fd66bb6c/samples/csharp_dotnetcore/05.multi-turn-prompt/Dialogs/UserProfileDialog.cs#L26-L44) and [new method](https://github.com/microsoft/BotBuilder-Samples/blob/c1e2eabeccac2c544e0c1dbac3f0fe92fd66bb6c/samples/csharp_dotnetcore/05.multi-turn-prompt/Dialogs/UserProfileDialog.cs#L101-L127)
   - JS: [in constructor](https://github.com/microsoft/BotBuilder-Samples/blob/c1e2eabeccac2c544e0c1dbac3f0fe92fd66bb6c/samples/javascript_nodejs/05.multi-turn-prompt/dialogs/userProfileDialog.js#L34-L48) and [new method](https://github.com/microsoft/BotBuilder-Samples/blob/c1e2eabeccac2c544e0c1dbac3f0fe92fd66bb6c/samples/javascript_nodejs/05.multi-turn-prompt/dialogs/userProfileDialog.js#L107-L128)
1. This also changes the logic in the following dialog step and the structure of the user profile object.
1. Also, C# folded the run helper method into the SDK proper, so there is no longer a DialogExtensions class in the C# sample.

## Expected behavior
The Python samples should match the behavior of the C# and JS samples.

## Additional context
Related issue in botbuilder-samples [2018](https://github.com/microsoft/BotBuilder-Samples/issues/2018)

[bug]

**Comment by JonathanFingold** [comment]
@tracyboehrer @mmiele Any comments?

**Comment by tracyboehrer** [comment]
@JonathanFingold None other than my comment the other day.  Is this causing a problem elsewhere, other than with parity?

**Comment by JonathanFingold** [comment]
@tracyboehrer - The associated how-to article includes all three languages. If the overall user interaction is different, it makes the article much more difficult to write and maintain. We could live with the discrepancy, but it would be an ongoing headache.

**Comment by tracyboehrer** [comment]
@JonathanFingold I should be able to get this done by no later than Thursday.  Hold off on finalizing the doc until then.

**Comment by tracyboehrer** [comment]
Updated in trboehre-move-samples staging branch.
