### ISSUE TITLE
Please fix typo (encounted) in templates

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/botbuilder-python#474]
## Version
What package version of the SDK are you using. master

## Describe the bug
The string `encounted` appears in the template, should be `encountered`.

## To Reproduce
1. Search the repo for the string `encounted`.
   https://github.com/microsoft/botbuilder-python/search?q=encounted&unscoped_q=encounted
1. Error: I currently get three hits, all in the templates.

## Expected behavior
We should eliminate typos in user-facing code, especially in templates.

## Additional context
re: BotBuilder-Samples PR [2025](https://github.com/microsoft/BotBuilder-Samples/pull/2025)

[bug]

**Comment by tracyboehrer** [comment]
Corrected in Samples staging branch:

https://github.com/microsoft/BotBuilder-Samples/tree/trboehrer-move-samples
