### ISSUE TITLE
Add codecov.io badge

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-python#51]
Example: [aiohttp](https://github.com/aio-libs/aiohttp/blob/master/README.rst) & [codecov.io](https://codecov.io/gh/aio-libs/aiohttp)

**Comment by d3vil0p3r** [comment]
@stevengum @yochay Can I take this?

**Comment by yochay** [comment]
Thanks you d3, please submit a PR.

**Comment by axelsrz** [comment]
With #256 we have a coveralls badge.
