### ISSUE TITLE
[PORT] BotAdapter changes (made for custom adapter / skills compat)

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#548]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3148

#3147  - Added additional ContinueConversationAsync overload for custom adapters for skills compatibility.
#3146 - Move 'BotIdentityKey' const to BotAdapter and made it public.

**Comment by garypretty** [comment]
Custom adapters do not currently exist for Python - just requires move 'BotIdentityKey' const to BotAdapter and made it public for parity.
