### ISSUE TITLE
[Samples] "POST 404 [conversationUpdate]" in Bot Emulator and Echo bot template

### ISSUE THREAD

**Issue by yannDroy** [Microsoft/botbuilder-python#55]
I cloned the repo and tried to run main.py from echo bot adapter template (with the async functions). But when I connect bot emulator to http://localhost:9000/api/messages I get a 404

**Comment by stevengum97** [comment]
@yannDroy, the route is http://localhost:9000 as shown [here](https://github.com/Microsoft/botbuilder-python/blob/master/samples/Echo.Connector.Bot.Adapter/main.py#L63). Can you try that and let us know if it works? Thanks!

**Comment by yannDroy** [comment]
Indeed, that was a nasty mistake from me. Thank you!
