### ISSUE TITLE
'BotFrameworkAdapter.receive' was never awaited

### ISSUE THREAD

**Issue by yannDroy** [Microsoft/botbuilder-python#56]
I cloned the repo and tried to run main.py from echo bot (not async one) and this is what I get when I run the program:

```
main.py:82: RuntimeWarning: coroutine 'BotFrameworkAdapter.receive' was never awaited
  self._adapter.receive(self.headers.get("Authorization"), activity)
```

**Comment by stevengum97** [comment]
@yannDroy, the non-async sample uses the [ConnectorClient](https://github.com/Microsoft/botbuilder-python/blob/master/libraries/botframework-connector/botframework/connector/connector_client.py) which contains synchronous methods, it doesn't use the BotFrameworkAdapter class. Can you share the code you using so we can better assist you?

**Comment by yannDroy** [comment]
It's okay now I must have been confused with the files and method. The sample works fine. Thank you!
