### ISSUE TITLE
[ConnectorClient] Issue with KIK Channel - HTTPSConnectionPool(host='kik.botframework.com', port=443):

### ISSUE THREAD

**Issue by hmundeepi** [Microsoft/botbuilder-python#57]
Hi Team,

I am using botbuilder-python sdk and its working fine for slack and skype channel but when i am running the "KIK" channel, I am getting the proper message from "KIK" but not able to send response back to "KIK" channel. Getting below error:

**ERROR:**
Exception in channel api send_reply- Error occurred in request., RetryError: HTTPSConnectionPool(host='kik.botframework.com', port=443): Max retries exceeded with url: /v3/conversations/{conversation_id}/activities (Caused by ResponseError('too many 500 error responses',))

**CODE:**

```py
credentials = MicrosoftAppCredentials(
    os.environ.get('MICROSOFT_CLIENT_ID'), 
    os.environ.get('MICROSOFT_APP_SECRET')
)
connector = ConnectorClient(credentials, base_url=ActivityRequestObject['serviceUrl'])
activity = Activity(
    type=ActivityTypes.message,
    channel_id=ActivityRequestObject['channelId'],
    recipient=ChannelAccount(id=ActivityRequestObject['from']['id']),
    from_property=ChannelAccount(id=ActivityRequestObject['recipient']['id']),
    text=result_string
)
connector.conversations.send_to_conversation(ActivityRequestObject['conversation']['id'], activity)
```

> While doing it manually by sending POST request it respond back with 400 error.

If any one have any idea what this issue is? As its working fine for slack and skype channel, I suppose either its a bug or data format for sending request to KIK channel is different.

**Comment by hmundeepi** [comment]
Hi Team,

For your information, please find below the URL, request header and request body:

**URL=**'https://kik.botframework.com/v3/conversations/{conversation_id}/activities'

**REQUEST_BODY=**{"type": "message", "channelId": "kik", "from": {"id": "dwarpal"}, "recipient": {"id": "hmundeepi"}, "text": "Hello, How may I help you?"}

**REQUEST_HEADER=**{'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '218'}

**{conversation_id}:** conversation id which I've received from the KIK channel.

**Comment by stevengum97** [comment]
@hmundeepi, can you try populating the `name` properties in the ChannelAccounts for the `recipient` and `from_property` attributes for your Activity? I was able to reproduce the error by only providing `id`. After setting up the code so it provides a `name` as well, the code was working again on Kik. 

I used the sample code from the Echo.Connector.Bot sample to reproduce the problem. To generate the [reply activity](https://github.com/Microsoft/botbuilder-python/blob/master/samples/Echo.Connector.Bot/main.py#L18L27) I used the below code:

```py
@staticmethod
def __create_reply_activity(request_activity, text):
    return Activity(
        type=ActivityTypes.message,
        channel_id=request_activity.channel_id,
        conversation=request_activity.conversation,
        recipient=request_activity.from_property,  # This contains the id and name
        from_property=request_activity.recipient,  # This contains the id and name
        text=text,
        service_url=request_activity.service_url)
```

**Comment by hmundeepi** [comment]
@stevengum97 thanks for your support. Its working fine after providing the name as well in **"from_property"** and **"recipient"** property.

recipient=ChannelAccount(id=ActivityRequestObject['from']['id'], name=**ActivityRequestObject['from']['name']**),
from_property=ChannelAccount(id=ActivityRequestObject['recipient']['id'], name=**ActivityRequestObject['recipient']['name']**)

Thanks again :+1:
