### ISSUE TITLE
[PORT] Nigao/readproperty

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#586]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3239

Update test files for the new features:
(1) read the value of a property, ask if a change is needed or not.
(2) send unexpected set message when set property is not expected.

**Comment by tracyboehrer** [comment]
Closing since Python doesn't have Adaptive
