### ISSUE TITLE
'ConversationReference' object is not subscriptable

### ISSUE THREAD

**Issue by sachitad** [microsoft/botbuilder-python#610]
## Version
botbuilder-core==4.7.0

## Describe the bug
I am trying to send proactive message via SDK. I am persisting conversation_reference object using pickle.dumps(). 

## To Reproduce
await ADAPTER.continue_conversation(
            conversation_reference,
            lambda turn_context: turn_context.send_activity("proactive hello"),
            bot_id=conversation_reference['bot']['id'],
        )

## Expected behavior
Proactive message should be sent

## Additional context

[bug]

**Comment by tracyboehrer** [comment]
@sachitad Have you compared this to the "16.proactive-messages" sample?  In that sample, the bot_id is the MicrosoftAppId.

**Comment by sachitad** [comment]
Thanks Tracy. That was the problem!
