### ISSUE TITLE
[PORT] Add PrivateAssets metadata to SourceLink.Create.CommandLine references

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#614]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3259

Added <PrivateAssets>all</PrivateAssets> to all project references to SourceLink.Create.CommandLine.

Addresses Issue #3211 , the "immediate fix" part.

**Comment by tracyboehrer** [comment]
NA for Python
