### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Piteryo** [Microsoft/botbuilder-python#62]
After building from source all modules and just importing the following line:
`from botbuilder.core import BotFrameworkAdapter`
I get 
![image](https://user-images.githubusercontent.com/4750178/38772605-b548fe40-4043-11e8-85b9-a08f743f238f.png)
Windows 10, x64, the same on Linux (CentOS)

**Comment by stevengum97** [comment]
@Piteryo, and @bruce-willis are you using Python 3 or Python 2?

**Comment by bruce-willis** [comment]
@stevengum97 python 3

**Comment by stevengum97** [comment]
What's the entire semver? At least 3.5?

**Comment by Piteryo** [comment]
@stevengum97, yeah, I have Python 3.5.2

**Comment by stevengum97** [comment]
Sorry about that, this syntax only became [valid in 3.6](https://www.python.org/dev/peps/pep-0526/). Can you upgrade to a Python version greater than 3.6? We're [targeting 3.6 and greater](https://github.com/Microsoft/botbuilder-python/blob/master/libraries/botbuilder-core/setup.py#L24). 

```py
    classifiers=[
        'Programming Language :: Python :: 3.6',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Development Status :: 3 - Alpha',
        'Topic :: Scientific/Engineering :: Artificial Intelligence',
    ]
```

**Comment by bruce-willis** [comment]
@stevengum97 managed to run using python 3.6.4. However, I had some problems with [sample in the wiki](https://github.com/Microsoft/botbuilder-python/blob/master/samples/Echo.Connector.Bot/main.py), but sample in [sample directory](https://github.com/Microsoft/botbuilder-python/blob/master/samples/Echo.Connector.Bot/main.py) works well.

Exception text:
> Exception happened during processing of request from ('127.0.0.1', 20773)
Traceback (most recent call last):
  File "C:\Anaconda3\lib\socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Anaconda3\lib\socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "C:\Anaconda3\lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Anaconda3\lib\socketserver.py", line 696, in __init__
    self.handle()
  File "C:\Anaconda3\lib\http\server.py", line 418, in handle
    self.handle_one_request()
  File "C:\Anaconda3\lib\http\server.py", line 406, in handle_one_request
    method()
  File ".\main.py", line 58, in do_POST
    self._adapter = BotFrameworkAdapter(APP_ID, APP_PASSWORD)
TypeError: \_\_init\_\_() takes 2 positional arguments but 3 were given.

If it matter - I left APP_ID and APP_PASSWORD blank and tried to connect both on `http://localhost:9000/api/messages` and `http://localhost:9000`

**Comment by bruce-willis** [comment]
@stevengum97, yeah. it's really seems like that the wiki simple needs to be updated. And his description too :smile::
>In your local terminal you should see the message 'Started http server on localhost:9000'
Start the Bot Framework Emulator, connect to your bot by using http://localhost:9000/api/messages.


![image](https://user-images.githubusercontent.com/21131904/38838313-3d480dae-41de-11e8-9e91-f934b5d50133.png)

*BTW:* the bot from [sample directory](https://github.com/Microsoft/botbuilder-python/blob/master/samples/Echo.Connector.Bot/main.py) responds both on `http://localhost:9000/api/messages` and `http://localhost:9000`

**Comment by stevengum97** [comment]
Then it probably responds to POST requests from any route, which is a little amusing in itself. 😃 

I'm going to leave this issue open for now until we get the wiki updated, if you run into any unrelated issues, please feel free to open up a new issue.

**Comment by stevengum97** [comment]
I've updated the wiki, so I'm going to close the issue.
