### ISSUE TITLE
[PORT] .NetCore 3.0 support updates

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#626]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3267

Fixes #3213 
Updated Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.csproj to target .netCore3.0 and standard.
Updated references to Microsoft.ApplicationInsights.AspNetCore 2.12 (has to be 2.8 or higher to support .netcore 3.0 as shown here: https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core)
Updated output path for cross compiled projects to use the $(TargetFramework) variable in the path.
Readded removed AsyncUsageAnalyzers to Microsoft.Bot.Builder.Integration.AspNet.Core.csproj

**Comment by gabog** [comment]
NA
