### ISSUE TITLE
[PORT] [Facebook Adapter] Add typing indicator support

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#639]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3130

## Description
The changes address the issue raised in bug [#3071](https://github.com/microsoft/botbuilder-dotnet/issues/3071) where the typing indicator is not supported in the .NET version of the adapter yet.

## Proposed changes
To display a `typing_on` [sender_action](https://developers.facebook.com/docs/messenger-platform/send-messages/sender-actions/) every time the bot prepares a message, we added the _SendMessage_ method in **FacebookHelper** which creates an extra activity with the required format for the Sender Action (note that `FacebookMessage.Message` needs to be null when Sender Actions are present) and then sends it along with the actual message activity using TurnContext [SendActivitiesAsync](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/TurnContext.cs#L218) method.
Sample bots have been modified accordingly, displaying typing indicators for messages, attachments, and templates.

**Comment by axelsrz** [comment]
N/A
