### ISSUE TITLE
Ensure UserAgent string is properly set

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/botbuilder-python#65]
The string should be:

```
Microsoft-BotFramework/3.1 (BotBuilder Python/${package version})
```

**Comment by stevengum97** [comment]
Work being done on [this branch](https://github.com/Microsoft/botbuilder-python/tree/v-stgum/userAgent).

**Comment by stevengum97** [comment]
PR created, @johnataylor will be doing the review.

**Comment by stevengum97** [comment]
PR was merged, closing issue.
