### ISSUE TITLE
[Skype For Business] There was an error sending this message to your bot: HTTP status code InternalServerError

### ISSUE THREAD

**Issue by vijaysaimutyala** [Microsoft/botbuilder-python#66]
I understand that the SDK is still under development and might have issues. I just wanted to inform this issue. I've configure the Python SDK with a bot built on top of Flask. The web chat control works perfectly fine. But when I add the bot to Skype for Business, it show the following message.
![skype](https://user-images.githubusercontent.com/7084628/39050006-4e4a3560-44c1-11e8-8bdd-76652a3e42d2.jpg)

When I check the Azure channels page, the error is as follows

> There was an error sending this message to your bot: HTTP status code InternalServerError

What I could see is that the Python backend is receiving the message perfectly from Skype For Business, but is failing to respond back. The python backend is hosted on Azure with domain *.azurewebsites.net which is https. 

Suggest any area where I could check up on the issue !

**Comment by vijaysaimutyala** [comment]
An update here. Published the same bot with REST API and it works !

**Comment by stevengum97** [comment]
Awesome! I'm glad it works.
