### ISSUE TITLE
[PORT] [Teams] adding helper to send messages to channel

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#661]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3292

# Changed projects
* Microsoft.Bot.Builder
* Microsoft.Bot.Builder.Tests
* Teams

[R8,teams]

**Comment by cleemullins** [comment]
@axelsrz This has been sitting since Jan. Can you look, and see if you can take the change and close this out? The C# code seems a very minor change.

**Comment by axelsrz** [comment]
After I looked at the code and had a conversation with @Virtual-Josh we realized this work has already been done in #653 and #654 so I'm closing this
