### ISSUE TITLE
[PORT] Add build YAML for Facebook functional test

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#666]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3262

## Description
Adds a YAML file to set up a pipeline to run the functional test for Facebook

This pull request depends on the test added in the PR #3250 
## Changes made
We added the file `botbuilder-dotnet-ci-facebook-test.yml` inside the build/yaml folder.

## How to use
The next steps will guide you through the configuration of a build pipeline based on this YAML file.

### Prerequisites
- Azure DevOps organization.
- Azure subscription. Required to create and delete Azure resources.
- App registration in [Azure Portal](https://portal.azure.com/), we need its **AppId** and **AppSecret**. More info [here](https://docs.microsoft.com/en-us/graph/auth-register-app-v2).
- Configure an Azure Connection Service (Steps below).
- Create a Facebook application and get the Facebook variables. (Steps below).

### Create a Facebook application and get the Facebook variables
For this step, you will need [ngrok](https://ngrok.com/) and the **botbuilder-dotnet** repository downloaded to run the test bot used locally.

1- Create or access a Facebook account for Developers (https://developers.facebook.com/).

2- Create a new App. Give a name to the app and click the Create App ID button.

3- In the Dashboard go to Add a Product and select Messenger by clicking on Set Up Button.
   - In the Access Tokens section, select a Facebook Page or create a new one. This is the page where the bot will be tested later.

> To create a page: Go to the [link](https://www.facebook.com/pages/creation/) and select Business or Brand Page. Complete the form with a name for the page and a category (Personal Blog is the category that requires fewer fields to complete). Click continue. You can skip the next two steps and you're done.

![image](https://user-images.githubusercontent.com/38112957/72457051-8abc9380-37a4-11ea-98ed-ad7fe607dfa6.png)
  - Once the page is added, click on the _Generate Token_ button and  copy the Token, this is required for the next steps and used as a variable when setting up the pipeline as _FacebookAccessToken_.
![image](https://user-images.githubusercontent.com/44245136/73399616-58438800-42c6-11ea-9041-5c67e7feb685.png)

4- Back to the developer's page, get the app credentials. Go to settings, basic and copy the app secret, this will be the variable _FacebookAppSecret_ in the other steps.
![image](https://user-images.githubusercontent.com/38112957/72461165-2e11a680-37ad-11ea-90ba-5a9545f4a545.png)

5- Set the tokens in appsettings.json file in your bot folder, located in the botbuilder-dotnet repository at `test/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.PrimaryTestBot`.
  - VerifyToken (crate one. It will be used to validate the callback URL sending a message)/
  - AppSecret (the one obtained in step 4).
  - AccessToken (the one obtained in step 3).

6- Run the bot by opening a command prompt in the bot folder and running `dotnet run` there, or opening the project with visual studio code and clicking on run.

7- Using a tunneling tool like [Ngrok](https://ngrok.com/download), expose the bot's endpoint. Open ngrok and run the next command line replacing `XXXX` for the port you are using to run the bot. 
`ngrok http XXXX -host-header="localhost:XXXX"`
![image](https://user-images.githubusercontent.com/38112957/72457500-7fb63300-37a5-11ea-9195-ae8bffe51a76.png)

8- Open your browser and go to http://localhost:4040/, where we can see all the requests to our bot, leave this page open.

9- Go back to the Facebook for Developers page and click on Messenger, Settings. In the Webhooks section, click on Add Callback URL button.
 - Complete the Callback URL with the ngrok https URL adding '/api/messages'. Fill in the Verify Token with the one set on your bot.
Click _Verify and Save_ button.
- Then, press the _Add Subscriptions_ button to subscribe to the following events: _messages_, _messaging_postbacks_, _messaging_optins_, _messaging_deliveries_.
Click the _Save_ button.

10- Go to the Page and click Add a Button.
![image](https://user-images.githubusercontent.com/38112957/72457706-fb17e480-37a5-11ea-8a4d-386ece70bd7f.png)
 - Under _Contact you_ drop down, select a Send Message button.
- Click on the _Next_ button.
 - Select Messenger.
 - Click the _Finish_ button.

12- Click on the button created and test your bot sending a message.

13- Go back to the ngrok's page we opened in step 7 and look for the message sent to the bot from Facebook and store the sender ID. This ID will be the variable _SenderId_ for the functional test and the pipeline. If the bot is running you will also have the answer from the bot, use the sender id from the message sent to the bot, or the recipient id from the message sent by the bot.
![image](https://user-images.githubusercontent.com/38112957/73073357-f59d5700-3e95-11ea-8efc-b52c5654ec13.png)

### Create an Azure Resource Manager service connection
This step is required to use your Azure Subscription for the Windows and Linux CI builds. If you already have a Connection Service configured, save its Connection name to use it later as _AzureSubscription_.
For more info go to [this link](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml).

1-  Navigate to Project settings -> Service Connections -> New service connection.
![image](https://user-images.githubusercontent.com/37461749/73199575-d7448f00-4113-11ea-8bb1-d85c7b92ba4c.png)

2- Select **Azure Resource Manager** and click Next. Then, select **Service principal (manual)**
![image](https://user-images.githubusercontent.com/37461749/73199960-a1ec7100-4114-11ea-8816-20320c57650b.png)

3- In the **New Azure Service Connection** section, complete the next fields. Then, click on **verify and save**. 
   - Subscription Id (stand for Azure Subscription Id)
   - Subscription Name
   - Services Principal Id
   - Service principal key
   - Tenant ID
   - Services connection name (Name used to refer to this service connection in the pipelines)
![image](https://user-images.githubusercontent.com/37461749/73202899-ce0af080-411a-11ea-91b6-a1849a0c02c3.png)

### Set up build pipeline
1. Create a new build pipeline. Then, select the _**Use classic editor**_ option.
![image](https://user-images.githubusercontent.com/37461749/73196597-a1e97280-410e-11ea-805a-7ab99ffee9e8.png)

2. Configure the repository and branch. Then, in the configuration as code, click on _**Apply**_ for the YAML file option. 
![image](https://user-images.githubusercontent.com/37461749/73197535-37393680-4110-11ea-9dfa-66e3ed45e825.png)

3. In section YAML, write the build name and select the build YAML file inside the folder `build/yaml` in the root of the directory.
![image](https://user-images.githubusercontent.com/38112957/70465856-a7c4bf00-1aa0-11ea-89cd-27e49ac28eb5.png)

4. In the Variables section add the following variables.
 - AppId (From app registration).
 - AppSecret* (From app registration).
 - AzureSubscription (Name of your [Azure Connection Service](#add-a-connection-service)).
 - FacebookAccessToken* (Page AccessToken obtained in the [create Facebook application](#create-a-facebook-application-and-get-facebook-variables) step).
 - FacebookAppSecret* (Your Facebook application's secret obtained in the [create Facebook application](#create-a-facebook-application-and-get-facebook-variables) step).
 - SenderId (Id from the user you are using to chat with your bot obtained in the [create Facebook application](#create-a-facebook-application-and-get-facebook-variables) step).
 - BotName (The name that your bot will have once deployed to Azure).
 - BotGroup (The name of the resource group to create in Azure).
*Set these variables as private.

5. (Optional) Configure the triggers for the pipeline. By default, this pipeline runs every time a pull request is created or a commit is made in the master branch.

## Testing
In the image below, you can see a pipeline set up using this YAML file running and the message sent to the Facebook chat by the bot.
![image](https://user-images.githubusercontent.com/38112957/72459749-2ef50900-37aa-11ea-84c7-051718b220b6.png)

[channel adapters]

**Comment by axelsrz** [comment]
N/A
