### ISSUE TITLE
[PORT] External Entities & Dynamic lists

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#667]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3300

Fix for #3156 which now enables external entity recognizers and dynamic lists for declarative LUIS recognizers.
*** Breaking change for declarative LUIS Recognizers ***
They now use expressions so to bind you need to do "=luis.settings.endpointKey" rather than "{luis.settings.endpointKey}".  There is also a PR to update bf-cli.

Dropped $role of lg and memorypath since not used.
Changed it so $role of expression would add string type.
Updated TestBot to include settings.
Moved all of the PropertyExpression stuff to its own library.  Once it no longer depends on .lg we can move it into the actual expression library.

# Changed projects
* Microsoft.Bot.Builder.AI.LUIS
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.Dialogs.Declarative
* Microsoft.Bot.Expressions.Properties
* Microsoft.Bot.Builder.AI.LUIS.Tests
* Microsoft.Bot.Builder.Ai.LUISV3.tests
* Microsoft.Bot.Builder.Dialogs.Adaptive.Templates.Tests
* Microsoft.Bot.Builder.Dialogs.Adaptive.Tests
* Microsoft.Bot.Builder.LanguageGeneration.Tests
* Microsoft.Bot.Builder.TestBot.Json

[R8,adaptive]

**Comment by tracyboehrer** [comment]
Closing as Python doesn't include Adaptive yet.
