### ISSUE TITLE
[PORT] Create test for waterfall cancellation telemetry

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#670]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3314

For https://github.com/microsoft/botbuilder-js/issues/1619

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Tests

**Comment by v-kydela** [comment]
@tomlm - Should I take care of this?
