### ISSUE TITLE
[PORT] Implement hash for App Insights session ID

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#673]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3317

Addresses this issue reported in JS https://github.com/microsoft/botbuilder-js/issues/1512

App Insights has a maximum session ID of 64 characters, but in some instances for some channels (such as reported with Teams) this may be exceeded due to conversation ID currently being used for session ID.  This PR hashes the conversation ID and sets this as the session ID.  It also adds an additional telemetry property to ensure we retain the original conversation ID within the telemetry.

The hashed ID is only used for Application Insights and the original conversation ID and activity are left untouched.

# Changed projects
* integration

**Comment by tracyboehrer** [comment]
Note: This takes place in telemetry_processor.py in Python.  Method get_request_body
