### ISSUE TITLE
[PORT] [Webex][Functional test] Add "Adapters" Test Category

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#676]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3309

### Description
This pull request adds the "Adapters" category to the Webex functional tests. 
This change allows executing the functional test without running the adapter's ones. 

### Specific Changes
- Add Adapters test category

**Comment by axelsrz** [comment]
N/A
