### ISSUE TITLE
[PORT] Update Functional Tests YAML files

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#677]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3310

### Description
This PR updates the functional tests YAML files to work with the Net Framework 3.1 version and to keep consistency betweem them.

### Changes made
- Twilio YAML: Change the set environment variables step to use uppercase: The use of lowercase can conflict with the use of pipeline variables set to hidden.

- Twilio, Slack, Webex, Nightly Build YAMLs: 
   - Change the target for the publish bot step: This is required when the project is multi-target and requires to specify which one to use, now we are using only 3.1.
   - Remove the build steps to replace them with the _ci-build-steps_ template.

[channel adapters]

**Comment by axelsrz** [comment]
N/A
