### ISSUE TITLE
[PORT] [Twilio Adapter] Add Twilio functional test

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#678]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3286

NOTE: YAML file to set up pipeline with this functional test in PR #3287 

### Description
This pull request adds a functional test for Twilio.

### Changes made
We added the class `TwilioNumberTests.cs` with the functional test for Twilio. It sends a message to the bot and then retrieve the last message of the conversation to assert the echo from the bot.

We moved the TwilioTestBot to the project to be used in the test and edited the deployment templates to include the required variables to deploy to Azure.

### Testing
In the image below you can see an example of the bot running in Azure and the test run locally pointing to that bot, with the answer from the bot to the cellphone used.
![image](https://user-images.githubusercontent.com/38112957/72819030-40775e80-3c4b-11ea-9c70-6155797ca7d3.png)

# Changed projects
* Adapters

[channel adapters]

**Comment by axelsrz** [comment]
N/A
