### ISSUE TITLE
[PORT] Update Prompt.cs

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#681]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3296

AppendChoices comment summary mentions it can be overriden, hence marking the method as virtual.

# Changed projects
* Microsoft.Bot.Builder.Dialogs

**Comment by tracyboehrer** [comment]
Closing.  Methods in Python are dynamic and don't require modifiers.
