### ISSUE TITLE
[PORT] Supporting iterate string by split function

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#687]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3328

closes #3279

Now split function can take a single parameter:
       split('hello'), new string[] { "h", "e", "l", "l", "o" }

Also if the seperator is a null, it will return same result as the seperator is string.Empty. If both input string and seperator are string.Empty or null, it will return a empty string array.
        split('hello',''), new string[] { "h", "e", "l", "l", "o" }
        split('',''), new string[] {  }
        split('hello',nullObj), new string[] { "h", "e", "l", "l", "o" }

If the input string is null, it will return string.Empty regardless the content of the non-empty seperator.
       split(nullObj,'e')", new string[] { string.Empty }

# Changed projects
* Microsoft.Bot.Expressions
* Microsoft.Bot.Expressions.Tests

**Comment by axelsrz** [comment]
N/A
