### ISSUE TITLE
[PORT] Do unexpected assigns before expected assigns.

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#696]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3334

Add HasEvents flag to entity event queues.

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.Dialogs.Adaptive.Tests

**Comment by tracyboehrer** [comment]
Closing.  No Adaptive support yet.
