### ISSUE TITLE
[PORT] [LG] treat everything after first '=' as value for the property

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#702]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3341

close: #3339 

Originally, if you want to input '=' in the structure value, an escape should be added. like:
```
# welcome(name)
[Activity
  text = hi, name \= @{name}
]
```

But now, we just treat the first equals mark as the key/value separator, so, we can write is as:
```
# welcome(name)
[Activity
  text = hi, name = @{name}
]
```
there is no need to write the backslash.

# Changed projects
* Microsoft.Bot.Builder.LanguageGeneration
* Microsoft.Bot.Builder.LanguageGeneration.Tests

**Comment by tracyboehrer** [comment]
Closing as Python doesn't include LG yet
