### ISSUE TITLE
[PORT] [OAuth] small oauth fix

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#705]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3333

The existing overload of GetOauthSignInLinkAsync function with a userId as argument isn't working. It was hardcoding directline, passing empty conversations etc. This PR is to fix that.

# Changed projects
* Microsoft.Bot.Builder

**Comment by tracyboehrer** [comment]
Closing.  Python was already populating the ConversationReference per the C# changes.
