### ISSUE TITLE
The bot referenced by the 'from' field is unrecognized - Unable to connect to Skype For Business channel

### ISSUE THREAD

**Issue by vijaysaimutyala** [Microsoft/botbuilder-python#71]
I'm trying to connect to Skype For Business channel using the Python SDK and could not. It returns the following error:

```
DEBUG:urllib3.connectionpool:https://webchat.botframework.com:443 "POST /v3/conversations/YmQ1MTkxZDkjc2lwOm1kbWJvdEBwZ29uZS5vbm1pY3Jvc29mdC5jb20%3D/activities HTTP/1.1" 400 128
DEBUG:msrest.exceptions:(MissingProperty) The bot referenced by the 'from' field is unrecognized
ERROR:root:Error is: 
Traceback (most recent call last):
  File "D:\home\site\wwwroot\main.py", line 127, in messages
    app.connector.conversations.send_to_conversation(activity['conversation']['id'], response_activity)
  File "D:\home\python364x64\lib\site-packages\botframework\connector\operations\conversations_operations.py", line 232, in send_to_conversation
    raise models.ErrorResponseException(self._deserialize, response)
botbuilder.schema.error_response_py3.ErrorResponseException: (MissingProperty) The bot referenced by the 'from' field is unrecognized
```
A conversation update activity from the bot:
```
{'type': 'conversationUpdate', 
'id': 'f5b9e798------', 
'timestamp': '2018-04-30T12:31:04.5652055Z', 
'serviceUrl': 'https://xxxxxxxx.lync.com/platformservice/tgt-xxxxxxxxxxxxxxxxxx/botframework', 
'channelId': 'skypeforbusiness', 
'from': {
  'id': 'sip:xxxxxxxxxx.com', 
  'name': 'xxxxxxxxxxxx'}, 
'conversation': 
{'isGroup': True,
'id': 'ZjJhYWZjZDYjcxxxxxxxxxxxxxxxxxxxxxxxxxxx'}, 
'recipient': 
{'id': 'sip:xxxxxxxxx.onmicrosoft.com', 
'name': 'sip:xxxxxx.onmicrosoft.com'}, 
'membersRemoved': 
[{'id': 'xxxxxxxxx', 
'name': 'xxxxxxxxxxxxxxx'}]}
```
I'm using the Flask sample from the [link](https://github.com/Microsoft/botbuilder-python/blob/702460a1606750650d8f7a20bdf7b11b763a5e1e/samples/Echo.Connector.Bot/main.py). This setup works well with the webchat but when I try talking to the bot from Skype For Business, I came accross this issue. There were similar issue logged in Bot builder SDK for .Net and node. The issues seems to be due to changes in v3.

I tried persisting the value from recipient field and sending it back with response but it didn't work. Am i missing something or is SFB channel not yet supported ?(REST API works fine with SFB using the same recipient and from values). Happy to provide more info if required.

**Comment by stevengum97** [comment]
Can you provide some reference links for the issues/questions in v3? Were they ever addressed? I'll reach out to other members on the team to see what exactly is going on here.

**Comment by vijaysaimutyala** [comment]
@stevengum97 Sure. I should've added them already. Please find them below

[Here](https://github.com/Microsoft/BotBuilder/issues/2450)
[here](https://github.com/botman/botman/issues/470)
[here](https://github.com/Microsoft/BotBuilder/issues/1322)
[here](https://github.com/Microsoft/BotBuilder/issues/1476)
[A not very helpful link](https://github.com/Microsoft/BotBuilder/issues/2857)

**Comment by stevengum97** [comment]
@vijaysaimutyala no problem! Are you using the code verbatim from [this commit](https://github.com/Microsoft/botbuilder-python/blob/702460a1606750650d8f7a20bdf7b11b763a5e1e/samples/Echo.Connector.Bot/main.py)? Going off of [issue 2450](https://github.com/Microsoft/BotBuilder/issues/2450) it would be great if we could see how you're constructing your outgoing activities.

**Comment by vijaysaimutyala** [comment]
Yes @stevengum97. I'm using the same exact code from that commit. I just replace the text ield with suitable answer after the but processes the user query. No other changes. Like I said above, webchat works fine but not Skype for Business.

**Comment by stevengum97** [comment]
Vijay, is this only affecting the `"conversationUpdate"` activities, or does it appear for any type of activity? 

> One more thing to note is that the recipient id and name fields are same in the message that comes from Skype for Business whereas for the message from WebChat, the id field contains the bot id and the name field has the bot's registered name on Azure Bot Service.

This is the correct behavior for Skype for Business 😄

**Comment by vijaysaimutyala** [comment]
Ah, I think so. Bcz the first event that occurs upon bringing up the bot on Skype is conversationUpdate. I never saw it go beyond that. The function that handles conversationUpdate throws the error as far as I remember. I'll check this behavior and get back Steven.

**Comment by vijaysaimutyala** [comment]
@stevengum97 Yes this is affecting conversationUpdate. The problem is that once the chat window is pulled up and a message is sent, the first event that occurs is conversationUpdate and this right away fails and endOfConversation event is sent. I've never seen a message event thats coming fro Skype for Business.

Logs below if it helps

`{'type': 'conversationUpdate', 
'id': '07981e56-d5c9-4a61-a8b4-3e402ded86bc', 'timestamp': '2018-05-07T05:45:34.4421472Z', 
'serviceUrl': 'https://webpoolbl20r04.infra.lync.com/platformservice/tgt-c4685276352c52b0a832c02a664d91ee/botframework', 
'channelId': 'skypeforbusiness', 
'from':
{'id': 'sip:mutyala.v@ab.com', 'name': 'Mutyala, VijaySai'}, 'conversation': {'isGroup': True, 'id': 'YTllNGRjNTkjc2lwOm1kbWJvdEBwZ29uZS5vbm1pY3Jvc29mdC5jb20='}, 'recipient': {'id': 'sip:bot@ab.onmicrosoft.com', 'name': 'sip:bot@ab.onmicrosoft.com'}, 'membersRemoved': [{'id': 'sip:mutyala.v@ab.com', 'name': 'Mutyala, VijaySai'}]}`

` {'type': 'endOfConversation', 
 'id': '9fccdfc2-bcd9-4912-aabb-96968c6137cb', 'timestamp': '2018-05-07T05:45:34.457773Z', 'serviceUrl': 'https://webpoolbl20r04.infra.lync.com/platformservice/tgt-c4685276352c52b0a832c02a664d91ee/botframework', 'channelId': 'skypeforbusiness', 'from': {'id': 'sip:bot@ab.onmicrosoft.com'}, 'conversation': {'isGroup': True, 'id': 'YTllNGRjNTkjc2lwOm1kbWJvdEBwZ29uZS5vbm1pY3Jvc29mdC5jb20='}, 'recipient': {'id': 'sip:bot@ab.onmicrosoft.com', 'name': 'sip:bot@ab.onmicrosoft.com'}}`

`DEBUG:msrest.exceptions:(MissingProperty) The bot referenced by the 'from' field is unrecognized
ERROR:root:Error is: 
Traceback (most recent call last):
  File "D:\home\site\wwwroot\main.py", line 107, in messages
    app.connector.conversations.send_to_conversation(activity['conversation']['id'], response_activity)
  File "D:\home\python364x64\lib\site-packages\botframework\connector\operations\conversations_operations.py", line 232, in send_to_conversation
    raise models.ErrorResponseException(self._deserialize, response)
botbuilder.schema.error_response_py3.ErrorResponseException: (MissingProperty) The bot referenced by the 'from' field is unrecognized`


I can proceed with REST API, but we're receiving random 401 errors.

**Comment by stevengum97** [comment]
@vijaysaimutyala, before I reach out to the SfB team, can you provide the previous two activities before the user is removed from the conversation? More specifically, the activities that appear when the user and the bot are added to the conversation via two `conversationUpdate` activities and if possible the message activity that is received by the bot when the user first interacts?

**Comment by vijaysaimutyala** [comment]
@stevengum97 I see only two activities.

1. conversationUpdate
2. endOfConversation

when working with SfB. Once the user sends a mesage, I receive a conversationUpdate event and immediately, the error is discussion is thrown and an endOfConversation is received. I'm not receiving any message events from the bot.

I just switched to Lync 2013 and the bot responds perfectly well. Referring to the [link](https://msdn.microsoft.com/en-us/skype/Skype-For-Business-Bot-Framework/docs/overview#supported-skype-for-business-versions), 

> Skype for Business Server 2015 is currently not a supported Microsoft Bot Framework channel.

Our users are currently using Skype for Business 2016 client. I need to check with my admin regarding the server version though.

From my previous logs, the serviceUrl is 

> 'https://webpoolbl20r04.infra.lync.com/platformservice/tgt-c4685276352c52b0a832c02a664d91ee/botframework'

Does the issue have anything to do with this ? I think the question might change to REST api supports SfB but Python SDK does not(Lync 2013 works with Python SDK)

**Comment by vijaysaimutyala** [comment]
Our SfB environment is Skype for Business Online which is officially supported [Channel support](https://msdn.microsoft.com/en-us/skype/Skype-For-Business-Bot-Framework/docs/overview#supported-skype-for-business-versions)

> The Skype for Business Bot Framework channel is currently supported for Skype for Business Online and Skype for Business Hybrid environments only.

**Comment by stevengum97** [comment]
@vijaysaimutyala yesterday I reached out to the Skype For Business team and am currently awaiting a response.

**Comment by vijaysaimutyala** [comment]
Thanks @stevengum97

**Comment by stevengum97** [comment]
@vijaysaimutyala, I've pinged the SfB team again, sorry for the delay...

**Comment by vijaysaimutyala** [comment]
Thanks for the updates @stevengum97.

**Comment by prateek05** [comment]
👍 upvote

**Comment by stevengum** [comment]
I'm very sorry for the lack up of updates; I'm still trying to get someone from the SfB team to respond.
