### ISSUE TITLE
[PORT] Updated MicrosoftGovernmentAppCredentials to support Skills in Azure Gov

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#710]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3353

Fixes https://github.com/microsoft/botbuilder-dotnet/issues/3233

Added constructor to MicrosoftGovernmentAppCredentials that takes OAuthScope to support skills in gov.
Updated BotFrameworkHttpClient and BotFrameworkAdapter to pass the OAuthScope to MicrosoftGovernmentAppCredentials
Added SimpleBotToBot functional test for testing.
Added Microsoft.Bot.Framework.Skills.sln to load skills test projects.

# Changed projects
* Microsoft.Bot.Builder
* Microsoft.Bot.Connector
* integration
* Microsoft.Bot.Connector.Tests

[Skills]

**Comment by tracyboehrer** [comment]
Blocked by lack of Gov support for Python.

**Comment by tracyboehrer** [comment]
Most of these changes have already been made.  Excluding the functional tests which Python has limited support for right now.

BotFrameworkHttpClient._get_app_credentials might be doing the correct thing.  Needs to be double checked, and switch to using MicrosoftGovernmentAppCredentials.
