### ISSUE TITLE
[PORT] Handle multiple property names on property assignment choice

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#712]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3351

This is a fix for #3348 

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.Dialogs.Adaptive.Tests

[Generated Dialogs,adaptive]

**Comment by tracyboehrer** [comment]
Closing.  No Adaptive in Python yet.
