### ISSUE TITLE
[PORT] Fix typos [mostly] in the bot.builder namespace

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#713]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3349

I also groomed some content, but did not perform a sanity check on all files touched.

# Changed projects
* Microsoft.Bot.Builder.ApplicationInsights
* Microsoft.Bot.Builder

[docs]

**Comment by Kaiqb** [comment]
n/a
