### ISSUE TITLE
[PORT] String interpolation enhancement

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#731]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3368

close: #3367

# Changed projects
* AdaptiveExpressions
* Microsoft.Bot.Builder.LanguageGeneration
* AdaptiveExpressions.Tests

[LG]

**Comment by axelsrz** [comment]
N/A
