### ISSUE TITLE
[PORT] Add SourceLink to these 3 projects

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#753]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3404

These 3 packages lack SourceLink. Adding it to them.

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.Dialogs.Debugging
* Microsoft.Bot.Builder.Dialogs.Declarative

**Comment by Kaiqb** [comment]
n/a
