### ISSUE TITLE
[PORT] [Doc] Add Build Process Documentation

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#756]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3378

## Description
This pull request adds the BotBuilder SDK Build Process Documentation. It contains general information about the build process configured for all repositories in the SDK. 

**Table of content**

- Short introduction 
- Build Process Comparison Table
- Pipeline details

The idea is to have an easy to read the documentation of the build process configured in the BotBuilder SDK. Also, it allows the user to have an idea of the parity level between the libraries.

**Comment by Kaiqb** [comment]
platform specific
