### ISSUE TITLE
[Auth] Port IAuthenticator change to support MSI authentication

### ISSUE THREAD

**Issue by carlosscastro** [microsoft/botbuilder-python#772]
as per PR https://github.com/microsoft/botbuilder-dotnet/pull/3255

Azure App Service (and several other resource types) has a Managed Service Identity feature which simplifies management of application identity - see Microsoft.Azure.Services.AppAuthentication for more information.

By having AdalAuthenticator derive from an interface, I can then inject my own MsiAuthenticator that uses AzureServiceTokenProvider to get the token to call the channels.

I can inject my MsiAuthenticator via overriding BuildCredentialsAsync on BotFrameworkHttpAdapter and returning a MsiAppCredentials class that, in turn, returns the MsiAuthenticator

**Comment by carlosscastro** [comment]
@rggammon I can assign this one to yourself if you are interested. The goal is to port your dotnet PR to python. If not interested, I can pick it up :) Thanks again for your contribution!

**Comment by rggammon** [comment]
Thanks @carlosscastro - I was looking at how this works in python. Perhaps I would inherit from BotFrameworkAdapter & override create_connector_client() to customize token getting in the python implementation? Happy to look at this, but I don't think the IAuthenticator change translates directly to python, so just need a few tips.

**Comment by tracyboehrer** [comment]
I think the closest translation would be to override a subclasses "__get_msal_app".  For example, see AppCredentials (base class) or MicrosoftAppCredentials or CertificateAppCredentials.  "__get_msal_app" is the MSAL object to get the token.  If that is the case I'd rename that method since the double-udnerscore indicate "private".

**Comment by carlosscastro** [comment]
Gabo and I had a conversation on this one. Since this IAuthenticator is in the deep auth layer and is not openly documented as an extension point, or particularly valuable as an extension point, we'll leave it as-is.
