### ISSUE TITLE
[PORT] Update TelemetryClient to enable tracking of dialog ('page') views

### ISSUE THREAD

**Issue by garypretty** [microsoft/botbuilder-python#789]
As per C# issue microsoft/botbuilder-dotnet#3441

C# PR -> microsoft/botbuilder-dotnet#3440

This is to support the ability to track user flows within application insights and understand how users move between dialogs within a conversation using the built in user flows / funnels pages within App Insights portal.

![flows2](https://user-images.githubusercontent.com/3900649/75298003-3ab40080-5829-11ea-8fa0-f63b85dae064.PNG)

[enhancement]

**Comment by denscollo** [comment]
We reviewed this issue and concluded that page view can't be ported to Python.

C# makes use of the PageViewTelemetry of Microsoft.ApplicationInisights library for its page view monitoring.
The Microsoft.ApplicationInisght-Python package is deprecated, and points to use opencensus-python instead, but we didn't find an implementation of the PageViewTelemetry class or equivalent in either.

If you have more information that could let us continue with this issue, please let us know.

Thanks
