### ISSUE TITLE
[PORT] Add additional null check in Telemetry

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#796]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3452

Fixes: #3442 

Similar to [this PR](https://github.com/microsoft/botbuilder-dotnet/pull/3436), but adds a null check I missed (plus an additional test).

From

```csharp
if (items.ContainsKey(TelemetryBotIdInitializer.BotActivityKey))
```

To

```csharp
if (items != null && items.ContainsKey(TelemetryBotIdInitializer.BotActivityKey))
```

# Changed projects
* integration

**Comment by tracyboehrer** [comment]
NA for Python
