### ISSUE TITLE
[PORT] clean up activityhandler and teamsactivityhandler

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#814]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3482

fixes #3446 

(duplicate code and new compiler warning introduced with sso fixes)

# Changed projects
* Microsoft.Bot.Builder
* Microsoft.Bot.Builder.Tests

**Comment by tracyboehrer** [comment]
Closing.  Already performed by Axel whilst addressing #793.  Released in 4.8.0 (R8)
