### ISSUE TITLE
Direct Line App Service Extension

### ISSUE THREAD

**Issue by jakeatmsft** [microsoft/botbuilder-python#829]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/botframework

Is Direct Line App Service Extension available in python sdk?
ref: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension?view=azure-bot-service-4.0

**Comment by stevengum** [comment]
Hi @jakeatmsft, unfortunately the Direct Line App Service Extension is not available in the Python SDK at this time, due to Linux App Services not supporting WebSockets.

(FYI @DDEFromOR)

**Comment by stevengum** [comment]
Small update for this issue, Linux App Services support WebSockets, and thus the Python SDK supports the Direct Line Speech channel (which uses WebSockets as its transport mechanism).

Unfortunately the Direct Line App Service Extension (_DL-ASE_) is available on only Windows App Services, not Linux App Services. The Bot Framework SDK for Python does not support DL-ASE at this time.
