### ISSUE TITLE
[PORT] Skill OAuth only change card action for emulator

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#834]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3503

There is code in the OAuthPrompt to change the sign in action of an OAuthCard to "openUrl" instead of "signin" for skills. This really only should be done for the emulator, as it impacts how WebChat handles the card.

# Changed projects
* Microsoft.Bot.Builder.Dialogs

**Comment by Kaiqb** [comment]
@tracyboehrer - could you put a milestone label on this?
