### ISSUE TITLE
[PORT] Add support for SSO to parent and child bot projects for manual testing

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#840]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3489

- Add support for SSO to parent and child bot projects for manual testing
- Fixed  a minor bug in oauthprompt

# Changed projects
* Skills

**Comment by johnataylor** [comment]
note parent and child are test projects

**Comment by gabog** [comment]
Hi @axelsrz, can you see if we really need this port? just close this issue if it doesn't apply
