### ISSUE TITLE
DotNet Parity Expose DialogContext in DialogTestClient

### ISSUE THREAD

**Issue by gabog** [microsoft/botbuilder-python#855]
The Python DialogTestClient is missing a new property that was added to C# in R8, here are the relevant changes that need to be ported:
https://github.com/microsoft/botbuilder-dotnet/pull/3474/files?file-filters%5B%5D=.cs&file-filters%5B%5D=.csproj#diff-cd997b1a4e0eead2ab97d4306dc01e5d

https://github.com/microsoft/botbuilder-dotnet/pull/3474/files?file-filters%5B%5D=.cs#diff-b9c1f832059ccb96a8441859a274d3b6

**Comment by tracyboehrer** [comment]
Closing.  Work already done in SkillDialog PR

https://github.com/microsoft/botbuilder-python/pull/757/commits/c4e66d9dee870676ef25864590fa91954ab0a9cf
