### ISSUE TITLE
Skills + OAuth: Differentiate between regular and skill mode when receiving tokens (Python)

### ISSUE THREAD

**Issue by clearab** [microsoft/botbuilder-python#917]
See [parent](https://github.com/microsoft/botframework-sdk/issues/5789)

When doing OAuth, and a Skill gets an activity, the skill thinks it is in regular mode and not skill mode, so it uses the wrong connector client.

The fix is to have the Token Service add an additional claim and have the SDK act accordingly and know in what mode it is based on the claim.

**Comment by cleemullins** [comment]
The code for this landed in C# today. Please check with @carlosscastro for details.
