### ISSUE TITLE
[PORT] Updated RunAsync to avoid sending EoC from the RootBot to the channel

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#942]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3735

Fixes #3699.

In this PR I refactored DialogExtensions to properly handle end of conversation in different scenarios and added unit tests for it. 

@stevengum, @tracyboehrer, @axelsrz:  The changes in [DialogExtensions](https://github.com/microsoft/botbuilder-dotnet/blob/gabog/SkillDialogFnTestsUpdates/libraries/Microsoft.Bot.Builder.Dialogs/DialogExtensions.cs), [DialogExtensionsTests](https://github.com/microsoft/botbuilder-dotnet/blob/gabog/SkillDialogFnTestsUpdates/tests/Microsoft.Bot.Builder.Dialogs.Tests/DialogExtensionsTests.cs) and [SkillHandler](https://github.com/microsoft/botbuilder-dotnet/pull/3735/files#diff-f589509021d3fc181ef8324e6d613f85) need to be ported to JS and Python.

As part of this PR, I also updated the DialogToDialog examples to align with the simpler version in Samples so we can manually test and debug the test scenarios **(these examples are optional and don't need to be ported or reviewed)**. 

Note: the branch name is not very descriptive but this PR is mainly about RunAsync fixes.
 

# Changed projects
* Microsoft.Bot.Builder.Dialogs
* Microsoft.Bot.Builder
* Microsoft.Bot.Builder.Dialogs.Tests

[P0,R9,Skills]

**Comment by gabog** [comment]
Duplicated, already being tracked in #936
