### ISSUE TITLE
[PORT] Add initial code owners to packages

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#953]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3746

Add in initial set of code owners to make Pull Requests and related operations more clear. 

[R9]

**Comment by cleemullins** [comment]
This is part of the debt/backlog work we'll take on in R10.

**Comment by cleemullins** [comment]
This would shold mirror, as closley as possible the CODEOWNERS file we've got in C#. That file is found here:
https://github.com/microsoft/botbuilder-dotnet/blob/master/.github/CODEOWNERS

**Comment by tracyboehrer** [comment]
Same owners?

**Comment by tracyboehrer** [comment]
Closing, duplicate to #1208
