### ISSUE TITLE
Python Functional Tests Don't Actually Execute

### ISSUE THREAD

**Issue by Zerryth** [microsoft/botbuilder-python#955]
## Version
4.8

## Describe the bug
In the Python SDK we actually have [functional tests written](https://github.com/microsoft/botbuilder-python/tree/master/libraries/functional-tests/tests), but we don't actually call the tests in a build pipeline. Seems to instead point to only `functionaltestbot/app.py` instead of a test file like `test_py_bot.py` in yaml file:
![image](https://user-images.githubusercontent.com/35248895/79405809-38794300-7f4a-11ea-9865-e82f58eb8ac5.png)

DevOps Pipeline:
![image](https://user-images.githubusercontent.com/35248895/79405861-5e064c80-7f4a-11ea-8b55-95a1afe9625b.png)

## Expected behavior
To have the functional tests execute when we run the build pipeline.

[bug]

**Comment by tracyboehrer** [comment]
Likely will be removing the functional-tests in Python as the tests in the new functional tests repo has a more complete functional test.
