### ISSUE TITLE
[PORT] Rename updateHandlers to deleteHandlers 

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#985]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3782

Fix typo in TurnContext.DeleteActivityInternalAsync

# Changed projects
* Microsoft.Bot.Builder

**Comment by v-kydela** [comment]
It looks like the typo isn't present in this repo because send, update, and delete all used a [shared function](https://github.com/microsoft/botbuilder-python/blob/master/libraries/botbuilder-core/botbuilder/core/turn_context.py#L277-L295) to handle their handlers
