### ISSUE TITLE
TypeError: post() takes from 1 to 3 positional arguments but 5 were given

### ISSUE THREAD

**Issue by aniztar** [Microsoft/botbuilder-python#99]
I am trying to run main.py from the folder - https://github.com/Microsoft/botbuilder-python/tree/master/samples/Echo-Connector-Bot/

I am getting this error when i send a message from the ms teams chat window.

```
Started http server
127.0.0.1 - - [19/Jul/2018 10:27:09] "POST / HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 46632)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 696, in __init__
    self.handle()
  File "/usr/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/lib/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "main.py", line 75, in do_POST
    self.__handle_message_activity(activity)
  File "main.py", line 44, in __handle_message_activity
    connector.conversations.send_to_conversation(reply.conversation.id, reply)
  File "/usr/local/lib/python3.6/dist-packages/botframework/connector/operations/conversations_operations.py", line 226, in send_to_conversation
    request = self._client.post(url, query_parameters, header_parameters, body_content)
TypeError: post() takes from 1 to 3 positional arguments but 5 were given
```

I am using these versions - (pip freeze output)

```
botbuilder==0.0.1
botbuilder-core==4.0.0a5
botbuilder-schema==4.0.0a5
botframework-connector==4.0.0a5
```

Am using any obsolete libraries?

**Comment by masyanru** [comment]
https://github.com/Microsoft/botbuilder-python/issues/93

**Comment by aniztar** [comment]
@masyanru Thanks for the link! Now I am not seeing the error!! 
Just a confirmation - Can botbuilder-python be used for an MS Teams bot for production? If so which is the most stable release?

**Comment by masyanru** [comment]
@aniztar, I think no, because this is just an alfa release. Just wait and test what we have now. )

**Comment by aniztar** [comment]
@masyanru  Okay. How about the C# and NodeJs versions? I really wanted to use Python since I wanted to add NLTK with it.

**Comment by masyanru** [comment]
@aniztar, Production bots should continue to be developed using the v3 SDK - [csharp](https://github.com/Microsoft/BotBuilder/tree/master/CSharp), [node](https://github.com/Microsoft/BotBuilder/tree/master/Node).

**Comment by aniztar** [comment]
@masyanru okay. Thanks a lot for everything. This can be closed now.
